rule win_shipshape_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2023-01-25"
        version = "1"
        description = "Detects win.shipshape."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.shipshape"
        malpedia_rule_date = "20230124"
        malpedia_hash = "2ee0eebba83dce3d019a90519f2f972c0fcf9686"
        malpedia_version = "20230125"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { c3 b8???????? 48 8a4801 40 84c9 75f8 }
            // n = 7, score = 100
            //   c3                   | ret                 
            //   b8????????           |                     
            //   48                   | dec                 eax
            //   8a4801               | mov                 cl, byte ptr [eax + 1]
            //   40                   | inc                 eax
            //   84c9                 | test                cl, cl
            //   75f8                 | jne                 0xfffffffa

        $sequence_1 = { ff15???????? 83f8ff 7516 8b15???????? 52 }
            // n = 5, score = 100
            //   ff15????????         |                     
            //   83f8ff               | cmp                 eax, -1
            //   7516                 | jne                 0x18
            //   8b15????????         |                     
            //   52                   | push                edx

        $sequence_2 = { 3d???????? 7cf1 56 8bf1 c1e603 3b9678b74000 0f851c010000 }
            // n = 7, score = 100
            //   3d????????           |                     
            //   7cf1                 | jl                  0xfffffff3
            //   56                   | push                esi
            //   8bf1                 | mov                 esi, ecx
            //   c1e603               | shl                 esi, 3
            //   3b9678b74000         | cmp                 edx, dword ptr [esi + 0x40b778]
            //   0f851c010000         | jne                 0x122

        $sequence_3 = { ffd6 85c0 0f84ef010000 8dbc24e4000000 83c9ff 33c0 8d9424fc030000 }
            // n = 7, score = 100
            //   ffd6                 | call                esi
            //   85c0                 | test                eax, eax
            //   0f84ef010000         | je                  0x1f5
            //   8dbc24e4000000       | lea                 edi, [esp + 0xe4]
            //   83c9ff               | or                  ecx, 0xffffffff
            //   33c0                 | xor                 eax, eax
            //   8d9424fc030000       | lea                 edx, [esp + 0x3fc]

        $sequence_4 = { 81ec00030000 8a15???????? 53 55 56 57 }
            // n = 6, score = 100
            //   81ec00030000         | sub                 esp, 0x300
            //   8a15????????         |                     
            //   53                   | push                ebx
            //   55                   | push                ebp
            //   56                   | push                esi
            //   57                   | push                edi

        $sequence_5 = { 56 e8???????? 56 e8???????? 83c408 eb09 56 }
            // n = 7, score = 100
            //   56                   | push                esi
            //   e8????????           |                     
            //   56                   | push                esi
            //   e8????????           |                     
            //   83c408               | add                 esp, 8
            //   eb09                 | jmp                 0xb
            //   56                   | push                esi

        $sequence_6 = { 83e103 f3a4 8d4c2434 50 51 e8???????? 8b6c2420 }
            // n = 7, score = 100
            //   83e103               | and                 ecx, 3
            //   f3a4                 | rep movsb           byte ptr es:[edi], byte ptr [esi]
            //   8d4c2434             | lea                 ecx, [esp + 0x34]
            //   50                   | push                eax
            //   51                   | push                ecx
            //   e8????????           |                     
            //   8b6c2420             | mov                 ebp, dword ptr [esp + 0x20]

        $sequence_7 = { 5e 32c0 5d 83c40c c20800 }
            // n = 5, score = 100
            //   5e                   | pop                 esi
            //   32c0                 | xor                 al, al
            //   5d                   | pop                 ebp
            //   83c40c               | add                 esp, 0xc
            //   c20800               | ret                 8

        $sequence_8 = { 2b7114 0330 8b401c 8b401c 2b421c 56 03c6 }
            // n = 7, score = 100
            //   2b7114               | sub                 esi, dword ptr [ecx + 0x14]
            //   0330                 | add                 esi, dword ptr [eax]
            //   8b401c               | mov                 eax, dword ptr [eax + 0x1c]
            //   8b401c               | mov                 eax, dword ptr [eax + 0x1c]
            //   2b421c               | sub                 eax, dword ptr [edx + 0x1c]
            //   56                   | push                esi
            //   03c6                 | add                 eax, esi

        $sequence_9 = { ffd5 85c0 7518 8b4c2414 51 }
            // n = 5, score = 100
            //   ffd5                 | call                ebp
            //   85c0                 | test                eax, eax
            //   7518                 | jne                 0x1a
            //   8b4c2414             | mov                 ecx, dword ptr [esp + 0x14]
            //   51                   | push                ecx

    condition:
        7 of them and filesize < 338386
}