rule win_webc2_table_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2023-03-28"
        version = "1"
        description = "Detects win.webc2_table."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.webc2_table"
        malpedia_rule_date = "20230328"
        malpedia_hash = "9d2d75cef573c1c2d861f5197df8f563b05a305d"
        malpedia_version = "20230407"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 8d85c0feffff 68???????? 50 ff15???????? 59 3bc3 59 }
            // n = 7, score = 100
            //   8d85c0feffff         | lea                 eax, [ebp - 0x140]
            //   68????????           |                     
            //   50                   | push                eax
            //   ff15????????         |                     
            //   59                   | pop                 ecx
            //   3bc3                 | cmp                 eax, ebx
            //   59                   | pop                 ecx

        $sequence_1 = { 33c0 8dbd4dffffff 889d4cffffff f3ab 66ab aa 6a18 }
            // n = 7, score = 100
            //   33c0                 | xor                 eax, eax
            //   8dbd4dffffff         | lea                 edi, [ebp - 0xb3]
            //   889d4cffffff         | mov                 byte ptr [ebp - 0xb4], bl
            //   f3ab                 | rep stosd           dword ptr es:[edi], eax
            //   66ab                 | stosw               word ptr es:[edi], ax
            //   aa                   | stosb               byte ptr es:[edi], al
            //   6a18                 | push                0x18

        $sequence_2 = { 7428 8b4df8 81f900100000 7323 8b45fc 50 881c01 }
            // n = 7, score = 100
            //   7428                 | je                  0x2a
            //   8b4df8               | mov                 ecx, dword ptr [ebp - 8]
            //   81f900100000         | cmp                 ecx, 0x1000
            //   7323                 | jae                 0x25
            //   8b45fc               | mov                 eax, dword ptr [ebp - 4]
            //   50                   | push                eax
            //   881c01               | mov                 byte ptr [ecx + eax], bl

        $sequence_3 = { 3bc3 a3???????? 7525 ff35???????? ff15???????? 837df405 }
            // n = 6, score = 100
            //   3bc3                 | cmp                 eax, ebx
            //   a3????????           |                     
            //   7525                 | jne                 0x27
            //   ff35????????         |                     
            //   ff15????????         |                     
            //   837df405             | cmp                 dword ptr [ebp - 0xc], 5

        $sequence_4 = { 50 e8???????? 56 8d85f4f8ffff 53 50 e8???????? }
            // n = 7, score = 100
            //   50                   | push                eax
            //   e8????????           |                     
            //   56                   | push                esi
            //   8d85f4f8ffff         | lea                 eax, [ebp - 0x70c]
            //   53                   | push                ebx
            //   50                   | push                eax
            //   e8????????           |                     

        $sequence_5 = { 3c20 7c08 3c21 7f08 }
            // n = 4, score = 100
            //   3c20                 | cmp                 al, 0x20
            //   7c08                 | jl                  0xa
            //   3c21                 | cmp                 al, 0x21
            //   7f08                 | jg                  0xa

        $sequence_6 = { 894dec ffd6 59 3bc3 59 }
            // n = 5, score = 100
            //   894dec               | mov                 dword ptr [ebp - 0x14], ecx
            //   ffd6                 | call                esi
            //   59                   | pop                 ecx
            //   3bc3                 | cmp                 eax, ebx
            //   59                   | pop                 ecx

        $sequence_7 = { 57 ff15???????? ff7710 ff15???????? 83c410 }
            // n = 5, score = 100
            //   57                   | push                edi
            //   ff15????????         |                     
            //   ff7710               | push                dword ptr [edi + 0x10]
            //   ff15????????         |                     
            //   83c410               | add                 esp, 0x10

        $sequence_8 = { 68???????? 50 e8???????? 8d85e4feffff 50 8d8570faffff }
            // n = 6, score = 100
            //   68????????           |                     
            //   50                   | push                eax
            //   e8????????           |                     
            //   8d85e4feffff         | lea                 eax, [ebp - 0x11c]
            //   50                   | push                eax
            //   8d8570faffff         | lea                 eax, [ebp - 0x590]

        $sequence_9 = { 894508 8d46ce 50 ffd7 8bf8 8d46cd }
            // n = 6, score = 100
            //   894508               | mov                 dword ptr [ebp + 8], eax
            //   8d46ce               | lea                 eax, [esi - 0x32]
            //   50                   | push                eax
            //   ffd7                 | call                edi
            //   8bf8                 | mov                 edi, eax
            //   8d46cd               | lea                 eax, [esi - 0x33]

    condition:
        7 of them and filesize < 49152
}