rule win_whitebird_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2023-03-28"
        version = "1"
        description = "Detects win.whitebird."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.whitebird"
        malpedia_rule_date = "20230328"
        malpedia_hash = "9d2d75cef573c1c2d861f5197df8f563b05a305d"
        malpedia_version = "20230407"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 8a4302 84c0 7408 3c01 }
            // n = 4, score = 400
            //   8a4302               | mov                 word ptr [ebp - 0xd4], ax
            //   84c0                 | mov                 eax, edi
            //   7408                 | mov                 word ptr [ebp - 0xd2], ax
            //   3c01                 | xor                 eax, eax

        $sequence_1 = { 8a4302 84c0 7408 3c01 7404 3c02 }
            // n = 6, score = 400
            //   8a4302               | dec                 eax
            //   84c0                 | cmp                 edx, 3
            //   7408                 | jl                  0x1c45
            //   3c01                 | dec                 ecx
            //   7404                 | add                 edx, 3
            //   3c02                 | inc                 ebp

        $sequence_2 = { 8a4302 84c0 7408 3c01 7404 }
            // n = 5, score = 400
            //   8a4302               | inc                 cx
            //   84c0                 | mov                 dword ptr [ebx], eax
            //   7408                 | mov                 al, byte ptr [0xffffd8e8]
            //   3c01                 | inc                 ebp
            //   7404                 | lea                 eax, [esp + 2]

        $sequence_3 = { 8a4301 3c01 7404 3c02 }
            // n = 4, score = 400
            //   8a4301               | mov                 word ptr [ebp - 0xd6], ax
            //   3c01                 | pop                 eax
            //   7404                 | mov                 word ptr [ebp - 0xd4], ax
            //   3c02                 | mov                 eax, edi

        $sequence_4 = { eb09 80f92f 0f95c1 80c13f }
            // n = 4, score = 400
            //   eb09                 | arpl                di, cx
            //   80f92f               | cmp                 edi, 3
            //   0f95c1               | jb                  0x1ee
            //   80c13f               | cmp                 edi, 0x101

        $sequence_5 = { 83d8ff 85c0 746f f685a4fbffff10 8d85d0fbffff 50 56 }
            // n = 7, score = 200
            //   83d8ff               | xor                 ecx, esp
            //   85c0                 | dec                 esp
            //   746f                 | lea                 ebx, [esp + 0x650]
            //   f685a4fbffff10       | dec                 ecx
            //   8d85d0fbffff         | mov                 ebx, dword ptr [ebx + 0x18]
            //   50                   | dec                 ecx
            //   56                   | mov                 ebp, dword ptr [ebx + 0x20]

        $sequence_6 = { ff15???????? 8b4dfc 66890459 43 3bde 7cee 8365f800 }
            // n = 7, score = 200
            //   ff15????????         |                     
            //   8b4dfc               | mov                 dword ptr [ebp - 0x528], eax
            //   66890459             | lea                 eax, [ebp - 0x504]
            //   43                   | push                0x100
            //   3bde                 | push                eax
            //   7cee                 | mov                 dword ptr [ebp - 0x524], ecx
            //   8365f800             | push                eax

        $sequence_7 = { ff15???????? 488b0d???????? ff15???????? 488b0d???????? e9???????? 488b442478 b9f4010000 }
            // n = 7, score = 200
            //   ff15????????         |                     
            //   488b0d????????       |                     
            //   ff15????????         |                     
            //   488b0d????????       |                     
            //   e9????????           |                     
            //   488b442478           | mov                 eax, 0x320
            //   b9f4010000           | dec                 ecx

        $sequence_8 = { e8???????? 6a01 56 ff75f4 ff15???????? }
            // n = 5, score = 200
            //   e8????????           |                     
            //   6a01                 | mov                 word ptr [ebp - 0x40c], ax
            //   56                   | add                 esp, 0xc
            //   ff75f4               | lea                 eax, [ebp - 0x41c]
            //   ff15????????         |                     

        $sequence_9 = { 8bd8 e8???????? 488bf0 483bc7 745f 4c8d4c2440 }
            // n = 6, score = 200
            //   8bd8                 | inc                 ebp
            //   e8????????           |                     
            //   488bf0               | xor                 ecx, ecx
            //   483bc7               | dec                 eax
            //   745f                 | lea                 edx, [esp + 0x24]
            //   4c8d4c2440           | dec                 eax

    condition:
        7 of them and filesize < 139264
}