rule win_stormwind_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2023-03-28"
        version = "1"
        description = "Detects win.stormwind."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.stormwind"
        malpedia_rule_date = "20230328"
        malpedia_hash = "9d2d75cef573c1c2d861f5197df8f563b05a305d"
        malpedia_version = "20230407"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 81e11f000080 7905 49 83c9e0 41 660f6f0d???????? 8bfa }
            // n = 7, score = 100
            //   81e11f000080         | and                 ecx, 0x8000001f
            //   7905                 | jns                 7
            //   49                   | dec                 ecx
            //   83c9e0               | or                  ecx, 0xffffffe0
            //   41                   | inc                 ecx
            //   660f6f0d????????     |                     
            //   8bfa                 | mov                 edi, edx

        $sequence_1 = { 83e11f c1f805 c1e106 030c85d8310510 eb02 8bcb f6412480 }
            // n = 7, score = 100
            //   83e11f               | and                 ecx, 0x1f
            //   c1f805               | sar                 eax, 5
            //   c1e106               | shl                 ecx, 6
            //   030c85d8310510       | add                 ecx, dword ptr [eax*4 + 0x100531d8]
            //   eb02                 | jmp                 4
            //   8bcb                 | mov                 ecx, ebx
            //   f6412480             | test                byte ptr [ecx + 0x24], 0x80

        $sequence_2 = { 89561c 894610 895614 7410 c74620ff970310 c7462414990310 }
            // n = 6, score = 100
            //   89561c               | mov                 dword ptr [esi + 0x1c], edx
            //   894610               | mov                 dword ptr [esi + 0x10], eax
            //   895614               | mov                 dword ptr [esi + 0x14], edx
            //   7410                 | je                  0x12
            //   c74620ff970310       | mov                 dword ptr [esi + 0x20], 0x100397ff
            //   c7462414990310       | mov                 dword ptr [esi + 0x24], 0x10039914

        $sequence_3 = { 8945e8 8bd9 c745e400000000 8bf8 c745fc00000000 }
            // n = 5, score = 100
            //   8945e8               | mov                 dword ptr [ebp - 0x18], eax
            //   8bd9                 | mov                 ebx, ecx
            //   c745e400000000       | mov                 dword ptr [ebp - 0x1c], 0
            //   8bf8                 | mov                 edi, eax
            //   c745fc00000000       | mov                 dword ptr [ebp - 4], 0

        $sequence_4 = { 83fa03 7ce6 8b7510 c60120 c6410420 6a0a }
            // n = 6, score = 100
            //   83fa03               | cmp                 edx, 3
            //   7ce6                 | jl                  0xffffffe8
            //   8b7510               | mov                 esi, dword ptr [ebp + 0x10]
            //   c60120               | mov                 byte ptr [ecx], 0x20
            //   c6410420             | mov                 byte ptr [ecx + 4], 0x20
            //   6a0a                 | push                0xa

        $sequence_5 = { c705????????687b0410 c705????????4c7b0410 c705????????787b0410 c705????????887b0410 c705????????947b0410 c705????????a07b0410 c705????????b07b0410 }
            // n = 7, score = 100
            //   c705????????687b0410     |     
            //   c705????????4c7b0410     |     
            //   c705????????787b0410     |     
            //   c705????????887b0410     |     
            //   c705????????947b0410     |     
            //   c705????????a07b0410     |     
            //   c705????????b07b0410     |     

        $sequence_6 = { 8d4ddc e8???????? 8d45dc c745dc74190410 8945ec 8d4db0 8d4608 }
            // n = 7, score = 100
            //   8d4ddc               | lea                 ecx, [ebp - 0x24]
            //   e8????????           |                     
            //   8d45dc               | lea                 eax, [ebp - 0x24]
            //   c745dc74190410       | mov                 dword ptr [ebp - 0x24], 0x10041974
            //   8945ec               | mov                 dword ptr [ebp - 0x14], eax
            //   8d4db0               | lea                 ecx, [ebp - 0x50]
            //   8d4608               | lea                 eax, [esi + 8]

        $sequence_7 = { 64a300000000 8bc2 8945ec 8bf1 c745e800000000 }
            // n = 5, score = 100
            //   64a300000000         | mov                 dword ptr fs:[0], eax
            //   8bc2                 | mov                 eax, edx
            //   8945ec               | mov                 dword ptr [ebp - 0x14], eax
            //   8bf1                 | mov                 esi, ecx
            //   c745e800000000       | mov                 dword ptr [ebp - 0x18], 0

        $sequence_8 = { 83fefe 0f87b2010000 8b4c243c 3bce 0f83ce000000 53 56 }
            // n = 7, score = 100
            //   83fefe               | cmp                 esi, -2
            //   0f87b2010000         | ja                  0x1b8
            //   8b4c243c             | mov                 ecx, dword ptr [esp + 0x3c]
            //   3bce                 | cmp                 ecx, esi
            //   0f83ce000000         | jae                 0xd4
            //   53                   | push                ebx
            //   56                   | push                esi

        $sequence_9 = { 8bf8 59 83ffff 7407 8b34bd286c0410 56 e8???????? }
            // n = 7, score = 100
            //   8bf8                 | mov                 edi, eax
            //   59                   | pop                 ecx
            //   83ffff               | cmp                 edi, -1
            //   7407                 | je                  9
            //   8b34bd286c0410       | mov                 esi, dword ptr [edi*4 + 0x10046c28]
            //   56                   | push                esi
            //   e8????????           |                     

    condition:
        7 of them and filesize < 741376
}