rule win_btcware_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2023-03-28"
        version = "1"
        description = "Detects win.btcware."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.btcware"
        malpedia_rule_date = "20230328"
        malpedia_hash = "9d2d75cef573c1c2d861f5197df8f563b05a305d"
        malpedia_version = "20230407"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 8d85a4d7ffff 50 8d85e4d8ffff 50 }
            // n = 4, score = 100
            //   8d85a4d7ffff         | lea                 eax, [ebp - 0x285c]
            //   50                   | push                eax
            //   8d85e4d8ffff         | lea                 eax, [ebp - 0x271c]
            //   50                   | push                eax

        $sequence_1 = { 8b4610 c6040800 83ff03 7ca9 8b7dd8 33db }
            // n = 6, score = 100
            //   8b4610               | mov                 eax, dword ptr [esi + 0x10]
            //   c6040800             | mov                 byte ptr [eax + ecx], 0
            //   83ff03               | cmp                 edi, 3
            //   7ca9                 | jl                  0xffffffab
            //   8b7dd8               | mov                 edi, dword ptr [ebp - 0x28]
            //   33db                 | xor                 ebx, ebx

        $sequence_2 = { 8b048540d04100 0fb6440828 83e040 5d c3 }
            // n = 5, score = 100
            //   8b048540d04100       | mov                 eax, dword ptr [eax*4 + 0x41d040]
            //   0fb6440828           | movzx               eax, byte ptr [eax + ecx + 0x28]
            //   83e040               | and                 eax, 0x40
            //   5d                   | pop                 ebp
            //   c3                   | ret                 

        $sequence_3 = { 83f810 7245 8b8da8feffff 40 3d00100000 }
            // n = 5, score = 100
            //   83f810               | cmp                 eax, 0x10
            //   7245                 | jb                  0x47
            //   8b8da8feffff         | mov                 ecx, dword ptr [ebp - 0x158]
            //   40                   | inc                 eax
            //   3d00100000           | cmp                 eax, 0x1000

        $sequence_4 = { 85c0 0f8449010000 68???????? 8d85d0d7ffff 50 ffd6 }
            // n = 6, score = 100
            //   85c0                 | test                eax, eax
            //   0f8449010000         | je                  0x14f
            //   68????????           |                     
            //   8d85d0d7ffff         | lea                 eax, [ebp - 0x2830]
            //   50                   | push                eax
            //   ffd6                 | call                esi

        $sequence_5 = { 0f8e6fffffff 83c8ff eb07 8b04cdc42f4100 5f }
            // n = 5, score = 100
            //   0f8e6fffffff         | jle                 0xffffff75
            //   83c8ff               | or                  eax, 0xffffffff
            //   eb07                 | jmp                 9
            //   8b04cdc42f4100       | mov                 eax, dword ptr [ecx*8 + 0x412fc4]
            //   5f                   | pop                 edi

        $sequence_6 = { 8d45e8 8b35???????? 6a00 50 ff75e8 68???????? 57 }
            // n = 7, score = 100
            //   8d45e8               | lea                 eax, [ebp - 0x18]
            //   8b35????????         |                     
            //   6a00                 | push                0
            //   50                   | push                eax
            //   ff75e8               | push                dword ptr [ebp - 0x18]
            //   68????????           |                     
            //   57                   | push                edi

        $sequence_7 = { 42 40 3bc7 7ce8 6a00 8d8c248c010000 6689745444 }
            // n = 7, score = 100
            //   42                   | inc                 edx
            //   40                   | inc                 eax
            //   3bc7                 | cmp                 eax, edi
            //   7ce8                 | jl                  0xffffffea
            //   6a00                 | push                0
            //   8d8c248c010000       | lea                 ecx, [esp + 0x18c]
            //   6689745444           | mov                 word ptr [esp + edx*2 + 0x44], si

        $sequence_8 = { 6800010000 8d85fcfcffff 50 68???????? ff15???????? 8b35???????? }
            // n = 6, score = 100
            //   6800010000           | push                0x100
            //   8d85fcfcffff         | lea                 eax, [ebp - 0x304]
            //   50                   | push                eax
            //   68????????           |                     
            //   ff15????????         |                     
            //   8b35????????         |                     

        $sequence_9 = { 83e809 7443 83e801 0f8501010000 c745e084414100 8b4508 8bcf }
            // n = 7, score = 100
            //   83e809               | sub                 eax, 9
            //   7443                 | je                  0x45
            //   83e801               | sub                 eax, 1
            //   0f8501010000         | jne                 0x107
            //   c745e084414100       | mov                 dword ptr [ebp - 0x20], 0x414184
            //   8b4508               | mov                 eax, dword ptr [ebp + 8]
            //   8bcf                 | mov                 ecx, edi

    condition:
        7 of them and filesize < 458752
}