rule win_ninerat_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-09-17"
        version = "1"
        description = "Detects win.ninerat."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ninerat"
        malpedia_rule_date = "20260916"
        malpedia_hash = "53a643781c18e08f4a50949af60172d837a0b6f6"
        malpedia_version = "20260917"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 4c898d48ffffff 8a8d69ffffff 80f101 741b 48c78570ffffff00000000 }
            // n = 5, score = 400
            //   4c898d48ffffff       | dec                 ecx
            //   8a8d69ffffff         | mov                 edi, edx
            //   80f101               | dec                 esp
            //   741b                 | mov                 dword ptr [ebp - 0x168], edi
            //   48c78570ffffff00000000     | dec    esp

        $sequence_1 = { 4c89bd98feffff 4889ce 4889d7 4c89c3 }
            // n = 4, score = 400
            //   4c89bd98feffff       | dec                 esp
            //   4889ce               | mov                 dword ptr [ebp - 0x168], edi
            //   4889d7               | dec                 eax
            //   4c89c3               | mov                 esi, ecx

        $sequence_2 = { 4c898550ffffff 488d9550ffffff 488bcb e8???????? 4889c1 }
            // n = 5, score = 400
            //   4c898550ffffff       | dec                 esp
            //   488d9550ffffff       | mov                 dword ptr [ebp - 0xe0], esp
            //   488bcb               | dec                 eax
            //   e8????????           |                     
            //   4889c1               | lea                 esi, [ebp - 0xf0]

        $sequence_3 = { 4c898510ffffff 488b8d58ffffff 48898d18ffffff 4c89a520ffffff 488db510ffffff 488dbd60ffffff }
            // n = 6, score = 400
            //   4c898510ffffff       | dec                 esp
            //   488b8d58ffffff       | mov                 dword ptr [ebp - 0x168], edi
            //   48898d18ffffff       | dec                 esp
            //   4c89a520ffffff       | mov                 dword ptr [ebp + 0x28], ecx
            //   488db510ffffff       | dec                 ecx
            //   488dbd60ffffff       | mov                 esi, ecx

        $sequence_4 = { 4c89bd98feffff 4c894d28 4989ce 4989d7 }
            // n = 4, score = 400
            //   4c89bd98feffff       | dec                 eax
            //   4c894d28             | mov                 edi, edx
            //   4989ce               | dec                 esp
            //   4989d7               | mov                 ebx, eax

        $sequence_5 = { 4c89a510ffffff 4c89ad18ffffff 48895518 4989cc }
            // n = 4, score = 400
            //   4c89a510ffffff       | mov                 edi, eax
            //   4c89ad18ffffff       | dec                 esp
            //   48895518             | mov                 dword ptr [ebp - 0x168], edi
            //   4989cc               | dec                 esp

        $sequence_6 = { 4c896da0 4c8975a8 4889cb 4989d4 4531ed 4531f6 }
            // n = 6, score = 400
            //   4c896da0             | dec                 esp
            //   4c8975a8             | mov                 dword ptr [ebp - 0xf0], eax
            //   4889cb               | dec                 eax
            //   4989d4               | mov                 ecx, dword ptr [ebp - 0xa8]
            //   4531ed               | dec                 eax
            //   4531f6               | mov                 dword ptr [ebp - 0xe8], ecx

        $sequence_7 = { 4c8995d8fcffff 4883bdd0fcffff00 740a 4983fe01 }
            // n = 4, score = 400
            //   4c8995d8fcffff       | mov                 edi, eax
            //   4883bdd0fcffff00     | inc                 ebp
            //   740a                 | xor                 ebp, ebp
            //   4983fe01             | mov                 esi, 1

        $sequence_8 = { 488b442450 48898424a8020000 660f6f842420010000 660fef8424a0020000 660f7f842420010000 }
            // n = 5, score = 100
            //   488b442450           | mov                 esp, ecx
            //   48898424a8020000     | xor                 eax, eax
            //   660f6f842420010000     | mov    dword ptr [ebp - 0xa4], eax
            //   660fef8424a0020000     | mov    dword ptr [ebp - 0x90], eax
            //   660f7f842420010000     | dec    esp

        $sequence_9 = { 4889842428010000 4c897c2450 488b442450 48898424a0020000 4c89642450 488b442450 48898424a8020000 }
            // n = 7, score = 100
            //   4889842428010000     | dec                 esp
            //   4c897c2450           | mov                 dword ptr [ebp - 0xf0], esp
            //   488b442450           | dec                 esp
            //   48898424a0020000     | mov                 dword ptr [ebp - 0xe8], ebp
            //   4c89642450           | dec                 eax
            //   488b442450           | mov                 dword ptr [ebp + 0x18], edx
            //   48898424a8020000     | dec                 ecx

        $sequence_10 = { 488d0d7f8f0100 e8???????? 488b442428 488905???????? 488d442428 }
            // n = 5, score = 100
            //   488d0d7f8f0100       | dec                 esp
            //   e8????????           |                     
            //   488b442428           | mov                 dword ptr [ebp - 0xf0], esp
            //   488905????????       |                     
            //   488d442428           | dec                 esp

        $sequence_11 = { 4c896c2450 488b442450 4889842490000000 4889742450 488b442450 4889842498000000 4c897c2450 }
            // n = 7, score = 100
            //   4c896c2450           | dec                 eax
            //   488b442450           | mov                 dword ptr [ebp + 0x18], edx
            //   4889842490000000     | dec                 ecx
            //   4889742450           | mov                 esp, ecx
            //   488b442450           | dec                 esp
            //   4889842498000000     | mov                 dword ptr [ebp - 0xf0], esp
            //   4c897c2450           | dec                 esp

        $sequence_12 = { 448d4307 498bcf 488d1547c40000 e8???????? 85c0 7413 }
            // n = 6, score = 100
            //   448d4307             | mov                 edx, dword ptr [ebp - 0x88]
            //   498bcf               | dec                 esp
            //   488d1547c40000       | mov                 dword ptr [ebp - 0xf0], esp
            //   e8????????           |                     
            //   85c0                 | dec                 esp
            //   7413                 | mov                 dword ptr [ebp - 0xe8], ebp

        $sequence_13 = { 4883ec20 8b1d???????? eb1d 488d0597390100 ffcb 488d0c9b 488d0cc8 }
            // n = 7, score = 100
            //   4883ec20             | mov                 dword ptr [ebp - 0xe8], ebp
            //   8b1d????????         |                     
            //   eb1d                 | dec                 eax
            //   488d0597390100       | mov                 dword ptr [ebp + 0x18], edx
            //   ffcb                 | dec                 ecx
            //   488d0c9b             | mov                 esp, ecx
            //   488d0cc8             | xor                 eax, eax

        $sequence_14 = { 7509 488d050b2f0100 eb04 4883c024 4883c428 c3 4883ec28 }
            // n = 7, score = 100
            //   7509                 | mov                 dword ptr [ebp - 0xe8], ebp
            //   488d050b2f0100       | dec                 eax
            //   eb04                 | mov                 dword ptr [ebp + 0x18], edx
            //   4883c024             | dec                 ecx
            //   4883c428             | mov                 esp, ecx
            //   c3                   | xor                 eax, eax
            //   4883ec28             | mov                 dword ptr [ebp - 0xa4], eax

        $sequence_15 = { 8bcf e8???????? 488bd7 4c8d0573cb0000 83e23f }
            // n = 5, score = 100
            //   8bcf                 | mov                 dword ptr [ebp - 0x328], edx
            //   e8????????           |                     
            //   488bd7               | dec                 eax
            //   4c8d0573cb0000       | cmp                 dword ptr [ebp - 0x330], 0
            //   83e23f               | je                  0x14

    condition:
        7 of them and filesize < 7709696
}