rule win_banatrix_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2023-07-11"
        version = "1"
        description = "Detects win.banatrix."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.banatrix"
        malpedia_rule_date = "20230705"
        malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
        malpedia_version = "20230715"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 897dcc 7514 8b7304 83b88400000000 }
            // n = 4, score = 200
            //   897dcc               | mov                 dword ptr [ebp - 0x34], edi
            //   7514                 | jne                 0x16
            //   8b7304               | mov                 esi, dword ptr [ebx + 4]
            //   83b88400000000       | cmp                 dword ptr [eax + 0x84], 0

        $sequence_1 = { ebd4 8b4320 893c24 89442404 }
            // n = 4, score = 200
            //   ebd4                 | jmp                 0xffffffd6
            //   8b4320               | mov                 eax, dword ptr [ebx + 0x20]
            //   893c24               | mov                 dword ptr [esp], edi
            //   89442404             | mov                 dword ptr [esp + 4], eax

        $sequence_2 = { 8b5704 0310 8b450c 83e00f 48 83f8ff 7409 }
            // n = 7, score = 200
            //   8b5704               | mov                 edx, dword ptr [edi + 4]
            //   0310                 | add                 edx, dword ptr [eax]
            //   8b450c               | mov                 eax, dword ptr [ebp + 0xc]
            //   83e00f               | and                 eax, 0xf
            //   48                   | dec                 eax
            //   83f8ff               | cmp                 eax, -1
            //   7409                 | je                  0xb

        $sequence_3 = { 0f45f9 8b4e10 85c9 7514 a840 7405 8b4a20 }
            // n = 7, score = 200
            //   0f45f9               | cmovne              edi, ecx
            //   8b4e10               | mov                 ecx, dword ptr [esi + 0x10]
            //   85c9                 | test                ecx, ecx
            //   7514                 | jne                 0x16
            //   a840                 | test                al, 0x40
            //   7405                 | je                  7
            //   8b4a20               | mov                 ecx, dword ptr [edx + 0x20]

        $sequence_4 = { 56 53 83ec10 8b5d08 85db 0f849c000000 837b1000 }
            // n = 7, score = 200
            //   56                   | push                esi
            //   53                   | push                ebx
            //   83ec10               | sub                 esp, 0x10
            //   8b5d08               | mov                 ebx, dword ptr [ebp + 8]
            //   85db                 | test                ebx, ebx
            //   0f849c000000         | je                  0xa2
            //   837b1000             | cmp                 dword ptr [ebx + 0x10], 0

        $sequence_5 = { c7042415070000 e8???????? 50 31c0 eb6f }
            // n = 5, score = 200
            //   c7042415070000       | mov                 dword ptr [esp], 0x715
            //   e8????????           |                     
            //   50                   | push                eax
            //   31c0                 | xor                 eax, eax
            //   eb6f                 | jmp                 0x71

        $sequence_6 = { eb20 8b7514 39f0 7306 c6040300 }
            // n = 5, score = 200
            //   eb20                 | jmp                 0x22
            //   8b7514               | mov                 esi, dword ptr [ebp + 0x14]
            //   39f0                 | cmp                 eax, esi
            //   7306                 | jae                 8
            //   c6040300             | mov                 byte ptr [ebx + eax], 0

        $sequence_7 = { 8b4508 6681384d5a 7409 c70424c1000000 eb78 8b5d08 }
            // n = 6, score = 200
            //   8b4508               | mov                 eax, dword ptr [ebp + 8]
            //   6681384d5a           | cmp                 word ptr [eax], 0x5a4d
            //   7409                 | je                  0xb
            //   c70424c1000000       | mov                 dword ptr [esp], 0xc1
            //   eb78                 | jmp                 0x7a
            //   8b5d08               | mov                 ebx, dword ptr [ebp + 8]

        $sequence_8 = { 8b4514 8b1a 668945e2 8b7204 83bb8c00000000 7509 c7042414070000 }
            // n = 7, score = 200
            //   8b4514               | mov                 eax, dword ptr [ebp + 0x14]
            //   8b1a                 | mov                 ebx, dword ptr [edx]
            //   668945e2             | mov                 word ptr [ebp - 0x1e], ax
            //   8b7204               | mov                 esi, dword ptr [edx + 4]
            //   83bb8c00000000       | cmp                 dword ptr [ebx + 0x8c], 0
            //   7509                 | jne                 0xb
            //   c7042414070000       | mov                 dword ptr [esp], 0x714

        $sequence_9 = { 89c7 89c1 c1ef1f 897dcc 89c7 }
            // n = 5, score = 200
            //   89c7                 | mov                 edi, eax
            //   89c1                 | mov                 ecx, eax
            //   c1ef1f               | shr                 edi, 0x1f
            //   897dcc               | mov                 dword ptr [ebp - 0x34], edi
            //   89c7                 | mov                 edi, eax

    condition:
        7 of them and filesize < 180224
}