rule win_acridrain_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2021-06-10"
        version = "1"
        description = "Detects win.acridrain."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.acridrain"
        malpedia_rule_date = "20210604"
        malpedia_hash = "be09d5d71e77373c0f538068be31a2ad4c69cfbd"
        malpedia_version = "20210616"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { ff74241c 8b442434 68???????? ff30 e8???????? 83c40c b815000000 }
            // n = 7, score = 200
            //   ff74241c             | push                dword ptr [esp + 0x1c]
            //   8b442434             | mov                 eax, dword ptr [esp + 0x34]
            //   68????????           |                     
            //   ff30                 | push                dword ptr [eax]
            //   e8????????           |                     
            //   83c40c               | add                 esp, 0xc
            //   b815000000           | mov                 eax, 0x15

        $sequence_1 = { ff33 e8???????? ff37 ff33 e8???????? 8b47d0 83c410 }
            // n = 7, score = 200
            //   ff33                 | push                dword ptr [ebx]
            //   e8????????           |                     
            //   ff37                 | push                dword ptr [edi]
            //   ff33                 | push                dword ptr [ebx]
            //   e8????????           |                     
            //   8b47d0               | mov                 eax, dword ptr [edi - 0x30]
            //   83c410               | add                 esp, 0x10

        $sequence_2 = { eb31 8b551c 8d4101 894620 8d0c89 8b4604 89548804 }
            // n = 7, score = 200
            //   eb31                 | jmp                 0x33
            //   8b551c               | mov                 edx, dword ptr [ebp + 0x1c]
            //   8d4101               | lea                 eax, dword ptr [ecx + 1]
            //   894620               | mov                 dword ptr [esi + 0x20], eax
            //   8d0c89               | lea                 ecx, dword ptr [ecx + ecx*4]
            //   8b4604               | mov                 eax, dword ptr [esi + 4]
            //   89548804             | mov                 dword ptr [eax + ecx*4 + 4], edx

        $sequence_3 = { c6471800 e8???????? 83c408 8bc6 5f 5e 5b }
            // n = 7, score = 200
            //   c6471800             | mov                 byte ptr [edi + 0x18], 0
            //   e8????????           |                     
            //   83c408               | add                 esp, 8
            //   8bc6                 | mov                 eax, esi
            //   5f                   | pop                 edi
            //   5e                   | pop                 esi
            //   5b                   | pop                 ebx

        $sequence_4 = { ff742424 ff742424 53 ff15???????? 8b7c2424 8bf0 c70700000000 }
            // n = 7, score = 200
            //   ff742424             | push                dword ptr [esp + 0x24]
            //   ff742424             | push                dword ptr [esp + 0x24]
            //   53                   | push                ebx
            //   ff15????????         |                     
            //   8b7c2424             | mov                 edi, dword ptr [esp + 0x24]
            //   8bf0                 | mov                 esi, eax
            //   c70700000000         | mov                 dword ptr [edi], 0

        $sequence_5 = { e8???????? 8be5 5d c3 3bbb18010000 722d 3bbb1c010000 }
            // n = 7, score = 200
            //   e8????????           |                     
            //   8be5                 | mov                 esp, ebp
            //   5d                   | pop                 ebp
            //   c3                   | ret                 
            //   3bbb18010000         | cmp                 edi, dword ptr [ebx + 0x118]
            //   722d                 | jb                  0x2f
            //   3bbb1c010000         | cmp                 edi, dword ptr [ebx + 0x11c]

        $sequence_6 = { c644880300 8b530c 85d2 7450 8b4618 8b4e20 394858 }
            // n = 7, score = 200
            //   c644880300           | mov                 byte ptr [eax + ecx*4 + 3], 0
            //   8b530c               | mov                 edx, dword ptr [ebx + 0xc]
            //   85d2                 | test                edx, edx
            //   7450                 | je                  0x52
            //   8b4618               | mov                 eax, dword ptr [esi + 0x18]
            //   8b4e20               | mov                 ecx, dword ptr [esi + 0x20]
            //   394858               | cmp                 dword ptr [eax + 0x58], ecx

        $sequence_7 = { bb07000000 8b542414 80bf9402000000 7460 80bf8a02000000 7457 8bb214010000 }
            // n = 7, score = 200
            //   bb07000000           | mov                 ebx, 7
            //   8b542414             | mov                 edx, dword ptr [esp + 0x14]
            //   80bf9402000000       | cmp                 byte ptr [edi + 0x294], 0
            //   7460                 | je                  0x62
            //   80bf8a02000000       | cmp                 byte ptr [edi + 0x28a], 0
            //   7457                 | je                  0x59
            //   8bb214010000         | mov                 esi, dword ptr [edx + 0x114]

        $sequence_8 = { e8???????? 8b4e30 83c408 8b4634 85c9 7405 894134 }
            // n = 7, score = 200
            //   e8????????           |                     
            //   8b4e30               | mov                 ecx, dword ptr [esi + 0x30]
            //   83c408               | add                 esp, 8
            //   8b4634               | mov                 eax, dword ptr [esi + 0x34]
            //   85c9                 | test                ecx, ecx
            //   7405                 | je                  7
            //   894134               | mov                 dword ptr [ecx + 0x34], eax

        $sequence_9 = { ff75f8 57 e8???????? 8b4dfc 83c40c 8bc6 33cd }
            // n = 7, score = 200
            //   ff75f8               | push                dword ptr [ebp - 8]
            //   57                   | push                edi
            //   e8????????           |                     
            //   8b4dfc               | mov                 ecx, dword ptr [ebp - 4]
            //   83c40c               | add                 esp, 0xc
            //   8bc6                 | mov                 eax, esi
            //   33cd                 | xor                 ecx, ebp

    condition:
        7 of them and filesize < 2244608
}