rule win_microbackdoor_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2021-06-10"
        version = "1"
        description = "Detects win.microbackdoor."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.microbackdoor"
        malpedia_rule_date = "20210604"
        malpedia_hash = "be09d5d71e77373c0f538068be31a2ad4c69cfbd"
        malpedia_version = "20210616"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 488d0d8a680000 448bc7 488bd6 e8???????? b801000000 488b5c2430 488b6c2438 }
            // n = 7, score = 100
            //   488d0d8a680000       | inc                 ecx
            //   448bc7               | mov                 eax, 0x208
            //   488bd6               | dec                 eax
            //   e8????????           |                     
            //   b801000000           | lea                 ecx, dword ptr [0x65d3]
            //   488b5c2430           | mov                 edx, eax
            //   488b6c2438           | inc                 ebp

        $sequence_1 = { eb14 ff15???????? 488d0d20710000 8bd0 }
            // n = 4, score = 100
            //   eb14                 | jne                 0xd94
            //   ff15????????         |                     
            //   488d0d20710000       | dec                 esp
            //   8bd0                 | mov                 esi, ecx

        $sequence_2 = { 448b4c2448 488b4c2450 488d442448 4c8bc3 ba01000000 4889442420 ff15???????? }
            // n = 7, score = 100
            //   448b4c2448           | je                  0x768
            //   488b4c2450           | dec                 ebp
            //   488d442448           | arpl                bp, ax
            //   4c8bc3               | xor                 edx, edx
            //   ba01000000           | dec                 eax
            //   4889442420           | mov                 ecx, eax
            //   ff15????????         |                     

        $sequence_3 = { e9???????? 4c8d4588 488d542470 488d4c2450 4533c9 ff15???????? 85c0 }
            // n = 7, score = 100
            //   e9????????           |                     
            //   4c8d4588             | jbe                 0x6fb
            //   488d542470           | add                 ebx, eax
            //   488d4c2450           | cmp                 ebx, edi
            //   4533c9               | jl                  0x5de
            //   ff15????????         |                     
            //   85c0                 | lea                 ecx, dword ptr [eax + 1]

        $sequence_4 = { c744243800000000 ff15???????? 488bd0 4885c0 7526 488bcb ff15???????? }
            // n = 7, score = 100
            //   c744243800000000     | mov                 dword ptr [esp + 0x30], eax
            //   ff15????????         |                     
            //   488bd0               | dec                 eax
            //   4885c0               | lea                 eax, dword ptr [esp + 0x40]
            //   7526                 | mov                 dword ptr [esp + 0x70], 0x14
            //   488bcb               | mov                 dword ptr [esp + 8], ecx
            //   ff15????????         |                     

        $sequence_5 = { 5b 5d c3 488d542458 488d0dd86a0000 41b810000000 }
            // n = 6, score = 100
            //   5b                   | dec                 eax
            //   5d                   | inc                 edx
            //   c3                   | cmp                 byte ptr [ecx + edx], 0
            //   488d542458           | ret                 
            //   488d0dd86a0000       | dec                 eax
            //   41b810000000         | mov                 dword ptr [esp + 0x58], edi

        $sequence_6 = { 4c8bc0 448bcb ff15???????? 488d4c2450 ff15???????? 488d542450 }
            // n = 6, score = 100
            //   4c8bc0               | dec                 ecx
            //   448bcb               | mov                 ebx, dword ptr [ebx + 0x18]
            //   ff15????????         |                     
            //   488d4c2450           | mov                 edx, esi
            //   ff15????????         |                     
            //   488d542450           | mov                 ecx, 0x40

        $sequence_7 = { 4889742418 48897c2420 4156 4883ec20 448b11 410fb7f1 }
            // n = 6, score = 100
            //   4889742418           | dec                 eax
            //   48897c2420           | add                 ecx, ebx
            //   4156                 | test                eax, eax
            //   4883ec20             | jne                 0x1d82
            //   448b11               | dec                 ebp
            //   410fb7f1             | mov                 eax, esp

        $sequence_8 = { 7435 48ffc0 483bc7 7cf2 }
            // n = 4, score = 100
            //   7435                 | dec                 eax
            //   48ffc0               | mov                 esi, ecx
            //   483bc7               | dec                 eax
            //   7cf2                 | mov                 ecx, dword ptr [ecx + 0x18]

        $sequence_9 = { 4c8d4588 488d5580 488d4c2478 4533c9 ff15???????? 85c0 7519 }
            // n = 7, score = 100
            //   4c8d4588             | mov                 dword ptr [esp + 0x38], esi
            //   488d5580             | mov                 dword ptr [esp + 0x30], 1
            //   488d4c2478           | cmp                 eax, -1
            //   4533c9               | je                  0xf62
            //   ff15????????         |                     
            //   85c0                 | test                eax, eax
            //   7519                 | dec                 esp

    condition:
        7 of them and filesize < 123904
}