rule win_agent_btz_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2021-06-10"
        version = "1"
        description = "Detects win.agent_btz."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.agent_btz"
        malpedia_rule_date = "20210604"
        malpedia_hash = "be09d5d71e77373c0f538068be31a2ad4c69cfbd"
        malpedia_version = "20210616"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { c74608ffffffff f644240801 7409 56 }
            // n = 4, score = 2500
            //   c74608ffffffff       | mov                 dword ptr [esi + 8], 0xffffffff
            //   f644240801           | test                byte ptr [esp + 8], 1
            //   7409                 | je                  0xb
            //   56                   | push                esi

        $sequence_1 = { 51 ffd6 8d54240c 52 ffd7 }
            // n = 5, score = 2500
            //   51                   | push                ecx
            //   ffd6                 | call                esi
            //   8d54240c             | lea                 edx, dword ptr [esp + 0xc]
            //   52                   | push                edx
            //   ffd7                 | call                edi

        $sequence_2 = { 50 ffd3 85c0 75d8 5f 5e 5b }
            // n = 7, score = 2500
            //   50                   | push                eax
            //   ffd3                 | call                ebx
            //   85c0                 | test                eax, eax
            //   75d8                 | jne                 0xffffffda
            //   5f                   | pop                 edi
            //   5e                   | pop                 esi
            //   5b                   | pop                 ebx

        $sequence_3 = { 895e08 895e04 c7461000000000 895e14 }
            // n = 4, score = 2400
            //   895e08               | mov                 dword ptr [esi + 8], ebx
            //   895e04               | mov                 dword ptr [esi + 4], ebx
            //   c7461000000000       | mov                 dword ptr [esi + 0x10], 0
            //   895e14               | mov                 dword ptr [esi + 0x14], ebx

        $sequence_4 = { ff15???????? b804000f00 8b4df4 64890d00000000 5f 5e }
            // n = 6, score = 2400
            //   ff15????????         |                     
            //   b804000f00           | mov                 eax, 0xf0004
            //   8b4df4               | mov                 ecx, dword ptr [ebp - 0xc]
            //   64890d00000000       | mov                 dword ptr fs:[0], ecx
            //   5f                   | pop                 edi
            //   5e                   | pop                 esi

        $sequence_5 = { c706???????? c7460c00000000 895e08 895e04 }
            // n = 4, score = 2400
            //   c706????????         |                     
            //   c7460c00000000       | mov                 dword ptr [esi + 0xc], 0
            //   895e08               | mov                 dword ptr [esi + 8], ebx
            //   895e04               | mov                 dword ptr [esi + 4], ebx

        $sequence_6 = { 56 6a00 68???????? 8935???????? e8???????? }
            // n = 5, score = 2300
            //   56                   | push                esi
            //   6a00                 | push                0
            //   68????????           |                     
            //   8935????????         |                     
            //   e8????????           |                     

        $sequence_7 = { 50 ff15???????? 894614 33c0 33db }
            // n = 5, score = 2300
            //   50                   | push                eax
            //   ff15????????         |                     
            //   894614               | mov                 dword ptr [esi + 0x14], eax
            //   33c0                 | xor                 eax, eax
            //   33db                 | xor                 ebx, ebx

        $sequence_8 = { 8d542408 52 c744240c30000000 c744241003000000 }
            // n = 4, score = 2200
            //   8d542408             | mov                 dword ptr [esi + 8], 0xffffffff
            //   52                   | test                byte ptr [esp + 8], 1
            //   c744240c30000000     | je                  0x10
            //   c744241003000000     | push                esi

        $sequence_9 = { 56 8bf1 8b4608 c706???????? 85c0 7413 }
            // n = 6, score = 2200
            //   56                   | push                esi
            //   8bf1                 | mov                 esi, ecx
            //   8b4608               | mov                 eax, dword ptr [esi + 8]
            //   c706????????         |                     
            //   85c0                 | test                eax, eax
            //   7413                 | je                  0x15

        $sequence_10 = { c706???????? 85c0 7413 83f8ff 740e 50 ff15???????? }
            // n = 7, score = 2200
            //   c706????????         |                     
            //   85c0                 | push                esi
            //   7413                 | add                 esp, 4
            //   83f8ff               | lea                 ecx, dword ptr [esp + 0xc]
            //   740e                 | push                ecx
            //   50                   | call                esi
            //   ff15????????         |                     

        $sequence_11 = { 50 ff15???????? c74608ffffffff f644240801 }
            // n = 4, score = 2200
            //   50                   | call                esi
            //   ff15????????         |                     
            //   c74608ffffffff       | lea                 edx, dword ptr [esp + 0xc]
            //   f644240801           | push                edx

        $sequence_12 = { 6a0a 68???????? 6a01 6a00 }
            // n = 4, score = 1400
            //   6a0a                 | push                0xa
            //   68????????           |                     
            //   6a01                 | push                1
            //   6a00                 | push                0

        $sequence_13 = { 51 6a00 6819000200 6a00 68???????? }
            // n = 5, score = 1400
            //   51                   | push                ecx
            //   6a00                 | push                0
            //   6819000200           | push                0x20019
            //   6a00                 | push                0
            //   68????????           |                     

        $sequence_14 = { 50 68???????? 6a01 68???????? e8???????? 83c410 }
            // n = 6, score = 1200
            //   50                   | test                eax, eax
            //   68????????           |                     
            //   6a01                 | je                  0x15
            //   68????????           |                     
            //   e8????????           |                     
            //   83c410               | cmp                 eax, -1

        $sequence_15 = { 6a01 6a04 6a01 68???????? }
            // n = 4, score = 1100
            //   6a01                 | push                1
            //   6a04                 | push                4
            //   6a01                 | push                1
            //   68????????           |                     

        $sequence_16 = { 83c020 50 e8???????? 83c404 33c0 }
            // n = 5, score = 1000
            //   83c020               | add                 eax, 0x20
            //   50                   | push                eax
            //   e8????????           |                     
            //   83c404               | add                 esp, 4
            //   33c0                 | xor                 eax, eax

        $sequence_17 = { 89461c 3dea000000 740b 3de5030000 }
            // n = 4, score = 1000
            //   89461c               | dec                 eax
            //   3dea000000           | mov                 ecx, dword ptr [edi]
            //   740b                 | dec                 eax
            //   3de5030000           | mov                 dword ptr [ecx + 8], eax

        $sequence_18 = { 50 e8???????? 83c408 6800010000 e8???????? }
            // n = 5, score = 1000
            //   50                   | mov                 dword ptr [esi + 0x28], eax
            //   e8????????           |                     
            //   83c408               | dec                 eax
            //   6800010000           | mov                 eax, dword ptr [esi + 0x38]
            //   e8????????           |                     

        $sequence_19 = { 6a01 68???????? e8???????? 83c414 5f 5e }
            // n = 6, score = 1000
            //   6a01                 | dec                 eax
            //   68????????           |                     
            //   e8????????           |                     
            //   83c414               | mov                 dword ptr [esi + 0x28], eax
            //   5f                   | dec                 eax
            //   5e                   | mov                 eax, dword ptr [esi + 0x38]

        $sequence_20 = { 7511 e8???????? 83c020 50 }
            // n = 4, score = 1000
            //   7511                 | jne                 0x13
            //   e8????????           |                     
            //   83c020               | add                 eax, 0x20
            //   50                   | push                eax

        $sequence_21 = { 0fb605???????? 66890d???????? 0fb60d???????? 660fafca 6603c8 }
            // n = 5, score = 1000
            //   0fb605????????       |                     
            //   66890d????????       |                     
            //   0fb60d????????       |                     
            //   660fafca             | imul                cx, dx
            //   6603c8               | add                 cx, ax

        $sequence_22 = { 6a01 e8???????? 50 e8???????? 83c414 }
            // n = 5, score = 1000
            //   6a01                 | push                1
            //   e8????????           |                     
            //   50                   | push                eax
            //   e8????????           |                     
            //   83c414               | add                 esp, 0x14

        $sequence_23 = { 56 8bd8 8d4304 8bf1 }
            // n = 4, score = 900
            //   56                   | push                esi
            //   8bd8                 | mov                 ebx, eax
            //   8d4304               | lea                 eax, dword ptr [ebx + 4]
            //   8bf1                 | mov                 esi, ecx

        $sequence_24 = { 56 8bf0 8b4624 57 }
            // n = 4, score = 900
            //   56                   | push                esi
            //   8bf0                 | mov                 esi, eax
            //   8b4624               | mov                 eax, dword ptr [esi + 0x24]
            //   57                   | push                edi

        $sequence_25 = { 668945f2 58 6a38 668945f4 58 6a78 }
            // n = 6, score = 900
            //   668945f2             | mov                 word ptr [ebp - 0xe], ax
            //   58                   | pop                 eax
            //   6a38                 | push                0x38
            //   668945f4             | mov                 word ptr [ebp - 0xc], ax
            //   58                   | pop                 eax
            //   6a78                 | push                0x78

        $sequence_26 = { 6800004004 53 53 8d4dd8 51 }
            // n = 5, score = 900
            //   6800004004           | push                0x4400000
            //   53                   | push                ebx
            //   53                   | push                ebx
            //   8d4dd8               | lea                 ecx, dword ptr [ebp - 0x28]
            //   51                   | push                ecx

        $sequence_27 = { 66894dec 59 6a25 58 6a30 668945f2 58 }
            // n = 7, score = 900
            //   66894dec             | mov                 word ptr [ebp - 0x14], cx
            //   59                   | pop                 ecx
            //   6a25                 | push                0x25
            //   58                   | pop                 eax
            //   6a30                 | push                0x30
            //   668945f2             | mov                 word ptr [ebp - 0xe], ax
            //   58                   | pop                 eax

        $sequence_28 = { 51 ff750c 8d4de4 51 ff7604 }
            // n = 5, score = 900
            //   51                   | push                ecx
            //   ff750c               | push                dword ptr [ebp + 0xc]
            //   8d4de4               | lea                 ecx, dword ptr [ebp - 0x1c]
            //   51                   | push                ecx
            //   ff7604               | push                dword ptr [esi + 4]

        $sequence_29 = { 668945f4 58 6a78 668945f6 58 668945f8 }
            // n = 6, score = 900
            //   668945f4             | mov                 word ptr [ebp - 0xc], ax
            //   58                   | pop                 eax
            //   6a78                 | push                0x78
            //   668945f6             | mov                 word ptr [ebp - 0xa], ax
            //   58                   | pop                 eax
            //   668945f8             | mov                 word ptr [ebp - 8], ax

        $sequence_30 = { 6a27 6a02 6a00 6a01 }
            // n = 4, score = 800
            //   6a27                 | push                0x27
            //   6a02                 | push                2
            //   6a00                 | push                0
            //   6a01                 | push                1

        $sequence_31 = { 8d8505feffff 50 e8???????? 83c40c }
            // n = 4, score = 700
            //   8d8505feffff         | dec                 eax
            //   50                   | mov                 eax, dword ptr [esi + 0x38]
            //   e8????????           |                     
            //   83c40c               | dec                 esp

        $sequence_32 = { e8???????? e8???????? 8bc8 e8???????? c745fcffffffff }
            // n = 5, score = 700
            //   e8????????           |                     
            //   e8????????           |                     
            //   8bc8                 | mov                 ecx, eax
            //   e8????????           |                     
            //   c745fcffffffff       | mov                 dword ptr [ebp - 4], 0xffffffff

        $sequence_33 = { 488b4338 33d2 488bce 448d4220 }
            // n = 4, score = 600
            //   488b4338             | dec                 eax
            //   33d2                 | mov                 eax, dword ptr [ebx + 0x38]
            //   488bce               | xor                 edx, edx
            //   448d4220             | dec                 eax

        $sequence_34 = { 488b4608 488b0e 48894628 488b4638 4c8d4c2450 448bc3 }
            // n = 6, score = 500
            //   488b4608             | cmp                 eax, -1
            //   488b0e               | je                  0x15
            //   48894628             | push                eax
            //   488b4638             | lea                 edx, dword ptr [esp + 8]
            //   4c8d4c2450           | push                edx
            //   448bc3               | mov                 dword ptr [esp + 0xc], 0x30

        $sequence_35 = { 488b4638 ff5060 894630 3de5030000 }
            // n = 4, score = 500
            //   488b4638             | test                eax, eax
            //   ff5060               | je                  0x1a
            //   894630               | cmp                 eax, -1
            //   3de5030000           | je                  0x1a

        $sequence_36 = { 488b0f 488901 488b07 488338ff }
            // n = 4, score = 500
            //   488b0f               | push                edi
            //   488901               | dec                 eax
            //   488b07               | sub                 esp, 0x40
            //   488338ff             | dec                 eax

        $sequence_37 = { 488bf0 c70005000000 85db 7415 }
            // n = 4, score = 500
            //   488bf0               | test                eax, eax
            //   c70005000000         | je                  0x17
            //   85db                 | mov                 esi, ecx
            //   7415                 | mov                 eax, dword ptr [esi + 8]

        $sequence_38 = { 488b0f 48894108 488b0f 488b4108 48894128 }
            // n = 5, score = 500
            //   488b0f               | dec                 eax
            //   48894108             | mov                 esi, dword ptr [esp + 0x68]
            //   488b0f               | dec                 eax
            //   488b4108             | add                 esp, 0x40
            //   48894128             | dec                 eax

        $sequence_39 = { 4156 4157 4883ec40 488b4138 }
            // n = 4, score = 500
            //   4156                 | mov                 eax, dword ptr [ecx + 8]
            //   4157                 | dec                 eax
            //   4883ec40             | mov                 dword ptr [ecx + 0x28], eax
            //   488b4138             | dec                 eax

        $sequence_40 = { 83c904 c1e803 448bc9 440fafc8 }
            // n = 4, score = 500
            //   83c904               | push                eax
            //   c1e803               | mov                 dword ptr [esi + 8], 0xffffffff
            //   448bc9               | test                byte ptr [esp + 8], 1
            //   440fafc8             | je                  0x18

        $sequence_41 = { 488b4638 488b0e 4c8d442450 4533c9 }
            // n = 4, score = 500
            //   488b4638             | test                eax, eax
            //   488b0e               | je                  0x17
            //   4c8d442450           | cmp                 eax, -1
            //   4533c9               | je                  0x17

        $sequence_42 = { 488b5738 488bce 8bd8 ff92e8010000 488b6c2458 }
            // n = 5, score = 500
            //   488b5738             | test                eax, eax
            //   488bce               | je                  0x15
            //   8bd8                 | cmp                 eax, -1
            //   ff92e8010000         | je                  0x15
            //   488b6c2458           | mov                 eax, dword ptr [esi + 8]

        $sequence_43 = { 488b4108 48894128 488b0f 48396928 }
            // n = 4, score = 500
            //   488b4108             | mov                 ecx, esi
            //   48894128             | inc                 esp
            //   488b0f               | lea                 eax, dword ptr [edx + 0x20]
            //   48396928             | dec                 eax

        $sequence_44 = { 488b0f 894130 eb06 488b07 896830 33c0 }
            // n = 6, score = 500
            //   488b0f               | xor                 ebp, ebp
            //   894130               | dec                 eax
            //   eb06                 | mov                 edi, ecx
            //   488b07               | dec                 ecx
            //   896830               | mov                 esi, eax
            //   33c0                 | dec                 eax

        $sequence_45 = { 488b07 896830 33c0 488b5c2458 488b6c2460 488b742468 4883c440 }
            // n = 7, score = 500
            //   488b07               | mov                 eax, dword ptr [ecx + 0x38]
            //   896830               | dec                 eax
            //   33c0                 | mov                 ecx, dword ptr [edi]
            //   488b5c2458           | dec                 eax
            //   488b6c2460           | mov                 eax, dword ptr [ecx + 8]
            //   488b742468           | dec                 eax
            //   4883c440             | mov                 dword ptr [ecx + 0x28], eax

        $sequence_46 = { 4889742420 57 4883ec40 33ed 488bf9 498bf0 }
            // n = 6, score = 500
            //   4889742420           | inc                 ecx
            //   57                   | push                edi
            //   4883ec40             | dec                 eax
            //   33ed                 | sub                 esp, 0x40
            //   488bf9               | dec                 eax
            //   498bf0               | mov                 eax, dword ptr [ecx + 0x38]

        $sequence_47 = { 488bcf c744242088130000 e8???????? 488b5738 }
            // n = 4, score = 500
            //   488bcf               | mov                 eax, dword ptr [esi + 8]
            //   c744242088130000     | test                eax, eax
            //   e8????????           |                     
            //   488b5738             | je                  0x17

        $sequence_48 = { 8d8594faffff 50 68???????? ff15???????? }
            // n = 4, score = 200
            //   8d8594faffff         | pop                 edi
            //   50                   | mov                 eax, 0xf0004
            //   68????????           |                     
            //   ff15????????         |                     

        $sequence_49 = { 0304b5100b4200 59 eb05 b8???????? }
            // n = 4, score = 100
            //   0304b5100b4200       | je                  0x18
            //   59                   | test                eax, eax
            //   eb05                 | je                  0x15
            //   b8????????           |                     

        $sequence_50 = { 001cbe 40 0023 d18a0688078a 46 }
            // n = 5, score = 100
            //   001cbe               | mov                 ecx, dword ptr [ebp - 0xc]
            //   40                   | mov                 dword ptr fs:[0], ecx
            //   0023                 | pop                 edi
            //   d18a0688078a         | pop                 esi
            //   46                   | pop                 ebx

        $sequence_51 = { 0304b5100b4200 59 5e eb05 }
            // n = 4, score = 100
            //   0304b5100b4200       | push                esi
            //   59                   | push                0
            //   5e                   | push                esi
            //   eb05                 | push                0

        $sequence_52 = { 0304b5100b4200 59 eb02 8bc3 }
            // n = 4, score = 100
            //   0304b5100b4200       | mov                 dword ptr [esi + 8], 0xffffffff
            //   59                   | test                byte ptr [esp + 8], 1
            //   eb02                 | test                eax, eax
            //   8bc3                 | je                  0x15

        $sequence_53 = { 030c85100b4200 eb02 8bcb f6412480 }
            // n = 4, score = 100
            //   030c85100b4200       | je                  0x1a
            //   eb02                 | cmp                 eax, -1
            //   8bcb                 | je                  0x1a
            //   f6412480             | mov                 esi, ecx

        $sequence_54 = { 0304b5100b4200 beffff0000 59 59 }
            // n = 4, score = 100
            //   0304b5100b4200       | je                  0x1c
            //   beffff0000           | test                eax, eax
            //   59                   | je                  0x15
            //   59                   | cmp                 eax, -1

        $sequence_55 = { 013d???????? 8b04b5100b4200 0500080000 3bc8 }
            // n = 4, score = 100
            //   013d????????         |                     
            //   8b04b5100b4200       | push                eax
            //   0500080000           | mov                 dword ptr [esi + 0x14], eax
            //   3bc8                 | xor                 eax, eax

    condition:
        7 of them and filesize < 5577728
}