rule win_powersniff_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2022-05-16"
        version = "1"
        description = "Detects win.powersniff."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.powersniff"
        malpedia_rule_date = "20220513"
        malpedia_hash = "7f4b2229e6ae614d86d74917f6d5b41890e62a26"
        malpedia_version = "20220516"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 0fb65108 0504010000 c1e208 0bd6 0fb6710a c1e208 0bd6 }
            // n = 7, score = 100
            //   0fb65108             | movzx               edx, byte ptr [ecx + 8]
            //   0504010000           | add                 eax, 0x104
            //   c1e208               | shl                 edx, 8
            //   0bd6                 | or                  edx, esi
            //   0fb6710a             | movzx               esi, byte ptr [ecx + 0xa]
            //   c1e208               | shl                 edx, 8
            //   0bd6                 | or                  edx, esi

        $sequence_1 = { c745f401000000 57 53 ff35???????? ff15???????? ff75fc ff15???????? }
            // n = 7, score = 100
            //   c745f401000000       | mov                 dword ptr [ebp - 0xc], 1
            //   57                   | push                edi
            //   53                   | push                ebx
            //   ff35????????         |                     
            //   ff15????????         |                     
            //   ff75fc               | push                dword ptr [ebp - 4]
            //   ff15????????         |                     

        $sequence_2 = { ffd6 ff75ec ffd6 b83c020000 eb17 83f8ff 7412 }
            // n = 7, score = 100
            //   ffd6                 | call                esi
            //   ff75ec               | push                dword ptr [ebp - 0x14]
            //   ffd6                 | call                esi
            //   b83c020000           | mov                 eax, 0x23c
            //   eb17                 | jmp                 0x19
            //   83f8ff               | cmp                 eax, -1
            //   7412                 | je                  0x14

        $sequence_3 = { 8906 8b4510 894608 c7460401000000 8b45fc }
            // n = 5, score = 100
            //   8906                 | mov                 dword ptr [esi], eax
            //   8b4510               | mov                 eax, dword ptr [ebp + 0x10]
            //   894608               | mov                 dword ptr [esi + 8], eax
            //   c7460401000000       | mov                 dword ptr [esi + 4], 1
            //   8b45fc               | mov                 eax, dword ptr [ebp - 4]

        $sequence_4 = { 83c104 83fa08 7cd6 c745fc???????? }
            // n = 4, score = 100
            //   83c104               | add                 ecx, 4
            //   83fa08               | cmp                 edx, 8
            //   7cd6                 | jl                  0xffffffd8
            //   c745fc????????       |                     

        $sequence_5 = { 83ec0c 8b473c 03c7 53 8b9880000000 }
            // n = 5, score = 100
            //   83ec0c               | sub                 esp, 0xc
            //   8b473c               | mov                 eax, dword ptr [edi + 0x3c]
            //   03c7                 | add                 eax, edi
            //   53                   | push                ebx
            //   8b9880000000         | mov                 ebx, dword ptr [eax + 0x80]

        $sequence_6 = { 8d45ec 50 689a030000 8d45fc }
            // n = 4, score = 100
            //   8d45ec               | lea                 eax, [ebp - 0x14]
            //   50                   | push                eax
            //   689a030000           | push                0x39a
            //   8d45fc               | lea                 eax, [ebp - 4]

        $sequence_7 = { 40 eb51 6a00 68424d5352 8d45fc 50 }
            // n = 6, score = 100
            //   40                   | inc                 eax
            //   eb51                 | jmp                 0x53
            //   6a00                 | push                0
            //   68424d5352           | push                0x52534d42
            //   8d45fc               | lea                 eax, [ebp - 4]
            //   50                   | push                eax

        $sequence_8 = { 47 8950fc 3b3e 0f8ca3feffff 5f 33c0 5b }
            // n = 7, score = 100
            //   47                   | inc                 edi
            //   8950fc               | mov                 dword ptr [eax - 4], edx
            //   3b3e                 | cmp                 edi, dword ptr [esi]
            //   0f8ca3feffff         | jl                  0xfffffea9
            //   5f                   | pop                 edi
            //   33c0                 | xor                 eax, eax
            //   5b                   | pop                 ebx

        $sequence_9 = { 3330 c1eb10 8975ec 8b75f4 c1ee18 8b34b590740010 c1e608 }
            // n = 7, score = 100
            //   3330                 | xor                 esi, dword ptr [eax]
            //   c1eb10               | shr                 ebx, 0x10
            //   8975ec               | mov                 dword ptr [ebp - 0x14], esi
            //   8b75f4               | mov                 esi, dword ptr [ebp - 0xc]
            //   c1ee18               | shr                 esi, 0x18
            //   8b34b590740010       | mov                 esi, dword ptr [esi*4 + 0x10007490]
            //   c1e608               | shl                 esi, 8

    condition:
        7 of them and filesize < 90112
}