rule win_terminator_rat_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2023-07-11"
        version = "1"
        description = "Detects win.terminator_rat."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.terminator_rat"
        malpedia_rule_date = "20230705"
        malpedia_hash = "42d0574f4405bd7d2b154d321d345acb18834a41"
        malpedia_version = "20230715"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { c78700fcffff2f010000 e8???????? 6a01 83f8ff 58 }
            // n = 5, score = 500
            //   c78700fcffff2f010000     | mov    dword ptr [edi - 0x400], 0x12f
            //   e8????????           |                     
            //   6a01                 | push                1
            //   83f8ff               | cmp                 eax, -1
            //   58                   | pop                 eax

        $sequence_1 = { 8bfc 81ec00040000 56 be00040000 8d8700fcffff 56 50 }
            // n = 7, score = 500
            //   8bfc                 | mov                 edi, esp
            //   81ec00040000         | sub                 esp, 0x400
            //   56                   | push                esi
            //   be00040000           | mov                 esi, 0x400
            //   8d8700fcffff         | lea                 eax, [edi - 0x400]
            //   56                   | push                esi
            //   50                   | push                eax

        $sequence_2 = { 391e 0f85cd000000 53 6880000000 6a04 53 6a01 }
            // n = 7, score = 500
            //   391e                 | cmp                 dword ptr [esi], ebx
            //   0f85cd000000         | jne                 0xd3
            //   53                   | push                ebx
            //   6880000000           | push                0x80
            //   6a04                 | push                4
            //   53                   | push                ebx
            //   6a01                 | push                1

        $sequence_3 = { 3452 c0c003 3443 c0c003 3448 c0c003 }
            // n = 6, score = 500
            //   3452                 | xor                 al, 0x52
            //   c0c003               | rol                 al, 3
            //   3443                 | xor                 al, 0x43
            //   c0c003               | rol                 al, 3
            //   3448                 | xor                 al, 0x48
            //   c0c003               | rol                 al, 3

        $sequence_4 = { 55 57 8bc7 83c004 837d0400 }
            // n = 5, score = 500
            //   55                   | push                ebp
            //   57                   | push                edi
            //   8bc7                 | mov                 eax, edi
            //   83c004               | add                 eax, 4
            //   837d0400             | cmp                 dword ptr [ebp + 4], 0

        $sequence_5 = { 746d 8b400c 8b00 3918 7464 }
            // n = 5, score = 500
            //   746d                 | je                  0x6f
            //   8b400c               | mov                 eax, dword ptr [eax + 0xc]
            //   8b00                 | mov                 eax, dword ptr [eax]
            //   3918                 | cmp                 dword ptr [eax], ebx
            //   7464                 | je                  0x66

        $sequence_6 = { 56 8bb501010000 ffb7e8feffff 8d854d010000 8987e8feffff 8b8541010000 c1e006 }
            // n = 7, score = 500
            //   56                   | push                esi
            //   8bb501010000         | mov                 esi, dword ptr [ebp + 0x101]
            //   ffb7e8feffff         | push                dword ptr [edi - 0x118]
            //   8d854d010000         | lea                 eax, [ebp + 0x14d]
            //   8987e8feffff         | mov                 dword ptr [edi - 0x118], eax
            //   8b8541010000         | mov                 eax, dword ptr [ebp + 0x141]
            //   c1e006               | shl                 eax, 6

        $sequence_7 = { 6800040000 50 e8???????? 8d8700fcffff c78700fcffff2b010000 50 e8???????? }
            // n = 7, score = 500
            //   6800040000           | push                0x400
            //   50                   | push                eax
            //   e8????????           |                     
            //   8d8700fcffff         | lea                 eax, [edi - 0x400]
            //   c78700fcffff2b010000     | mov    dword ptr [edi - 0x400], 0x12b
            //   50                   | push                eax
            //   e8????????           |                     

        $sequence_8 = { 395e08 7439 ffb7f0fbffff ff5531 }
            // n = 4, score = 500
            //   395e08               | cmp                 dword ptr [esi + 8], ebx
            //   7439                 | je                  0x3b
            //   ffb7f0fbffff         | push                dword ptr [edi - 0x410]
            //   ff5531               | call                dword ptr [ebp + 0x31]

        $sequence_9 = { 8b4610 018539010000 395e14 75d0 }
            // n = 4, score = 500
            //   8b4610               | mov                 eax, dword ptr [esi + 0x10]
            //   018539010000         | add                 dword ptr [ebp + 0x139], eax
            //   395e14               | cmp                 dword ptr [esi + 0x14], ebx
            //   75d0                 | jne                 0xffffffd2

    condition:
        7 of them and filesize < 73728
}