rule win_rustock_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-05-04"
        version = "1"
        description = "Detects win.rustock."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rustock"
        malpedia_rule_date = "20260422"
        malpedia_hash = "a182e35da64e6d71cb55f125c4d4225196523f14"
        malpedia_version = "20260504"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 0f848b000000 8365fc00 83c003 83e0fc }
            // n = 4, score = 100
            //   0f848b000000         | je                  0x91
            //   8365fc00             | and                 dword ptr [ebp - 4], 0
            //   83c003               | add                 eax, 3
            //   83e0fc               | and                 eax, 0xfffffffc

        $sequence_1 = { 8b0d???????? 09fe f7d1 b9???????? 29d1 }
            // n = 5, score = 100
            //   8b0d????????         |                     
            //   09fe                 | or                  esi, edi
            //   f7d1                 | not                 ecx
            //   b9????????           |                     
            //   29d1                 | sub                 ecx, edx

        $sequence_2 = { 29c3 051c3367d0 29d8 29cb 83c1ff ebb5 }
            // n = 6, score = 100
            //   29c3                 | sub                 ebx, eax
            //   051c3367d0           | add                 eax, 0xd067331c
            //   29d8                 | sub                 eax, ebx
            //   29cb                 | sub                 ebx, ecx
            //   83c1ff               | add                 ecx, -1
            //   ebb5                 | jmp                 0xffffffb7

        $sequence_3 = { ff15???????? 85c0 7471 8b7de0 8d45b8 50 ff15???????? }
            // n = 7, score = 100
            //   ff15????????         |                     
            //   85c0                 | test                eax, eax
            //   7471                 | je                  0x73
            //   8b7de0               | mov                 edi, dword ptr [ebp - 0x20]
            //   8d45b8               | lea                 eax, [ebp - 0x48]
            //   50                   | push                eax
            //   ff15????????         |                     

        $sequence_4 = { 7404 802700 47 ff06 8b5d0c }
            // n = 5, score = 100
            //   7404                 | je                  6
            //   802700               | and                 byte ptr [edi], 0
            //   47                   | inc                 edi
            //   ff06                 | inc                 dword ptr [esi]
            //   8b5d0c               | mov                 ebx, dword ptr [ebp + 0xc]

        $sequence_5 = { da81e53a558c b9157556b8 af 44 42 }
            // n = 5, score = 100
            //   da81e53a558c         | fiadd               dword ptr [ecx - 0x73aac51b]
            //   b9157556b8           | mov                 ecx, 0xb8567515
            //   af                   | scasd               eax, dword ptr es:[edi]
            //   44                   | inc                 esp
            //   42                   | inc                 edx

        $sequence_6 = { 8067ff00 8365fc00 803800 0f84d6000000 8a08 80f920 7405 }
            // n = 7, score = 100
            //   8067ff00             | and                 byte ptr [edi - 1], 0
            //   8365fc00             | and                 dword ptr [ebp - 4], 0
            //   803800               | cmp                 byte ptr [eax], 0
            //   0f84d6000000         | je                  0xdc
            //   8a08                 | mov                 cl, byte ptr [eax]
            //   80f920               | cmp                 cl, 0x20
            //   7405                 | je                  7

        $sequence_7 = { 57 ff15???????? 3bc6 7407 50 ff15???????? }
            // n = 6, score = 100
            //   57                   | push                edi
            //   ff15????????         |                     
            //   3bc6                 | cmp                 eax, esi
            //   7407                 | je                  9
            //   50                   | push                eax
            //   ff15????????         |                     

        $sequence_8 = { 7409 ff75d0 e8???????? 59 395de0 7409 }
            // n = 6, score = 100
            //   7409                 | je                  0xb
            //   ff75d0               | push                dword ptr [ebp - 0x30]
            //   e8????????           |                     
            //   59                   | pop                 ecx
            //   395de0               | cmp                 dword ptr [ebp - 0x20], ebx
            //   7409                 | je                  0xb

        $sequence_9 = { 8d6424fc c70424bc070100 5e 8d6424fc 891c24 5b }
            // n = 6, score = 100
            //   8d6424fc             | lea                 esp, [esp - 4]
            //   c70424bc070100       | mov                 dword ptr [esp], 0x107bc
            //   5e                   | pop                 esi
            //   8d6424fc             | lea                 esp, [esp - 4]
            //   891c24               | mov                 dword ptr [esp], ebx
            //   5b                   | pop                 ebx

    condition:
        7 of them and filesize < 565248
}