rule win_alreay_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2022-04-08"
        version = "1"
        description = "Describes win.alreay."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.alreay"
        malpedia_rule_date = "20220405"
        malpedia_hash = "ecd38294bd47d5589be5cd5490dc8bb4804afc2a"
        malpedia_version = ""
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 8937 8b742418 83c404 8b7c2418 85ff 742f 8b4c2424 }
            // n = 7, score = 100
            //   8937                 | mov                 dword ptr [edi], esi
            //   8b742418             | mov                 esi, dword ptr [esp + 0x18]
            //   83c404               | add                 esp, 4
            //   8b7c2418             | mov                 edi, dword ptr [esp + 0x18]
            //   85ff                 | test                edi, edi
            //   742f                 | je                  0x31
            //   8b4c2424             | mov                 ecx, dword ptr [esp + 0x24]

        $sequence_1 = { 8b4704 8b4c2440 53 55 50 8d542418 51 }
            // n = 7, score = 100
            //   8b4704               | mov                 eax, dword ptr [edi + 4]
            //   8b4c2440             | mov                 ecx, dword ptr [esp + 0x40]
            //   53                   | push                ebx
            //   55                   | push                ebp
            //   50                   | push                eax
            //   8d542418             | lea                 edx, dword ptr [esp + 0x18]
            //   51                   | push                ecx

        $sequence_2 = { 8b8794000000 8b9790000000 3bd8 0f8291000000 7708 3bea 0f8687000000 }
            // n = 7, score = 100
            //   8b8794000000         | mov                 eax, dword ptr [edi + 0x94]
            //   8b9790000000         | mov                 edx, dword ptr [edi + 0x90]
            //   3bd8                 | cmp                 ebx, eax
            //   0f8291000000         | jb                  0x97
            //   7708                 | ja                  0xa
            //   3bea                 | cmp                 ebp, edx
            //   0f8687000000         | jbe                 0x8d

        $sequence_3 = { 8d542424 51 8d44240c 52 50 e8???????? 83c40c }
            // n = 7, score = 100
            //   8d542424             | lea                 edx, dword ptr [esp + 0x24]
            //   51                   | push                ecx
            //   8d44240c             | lea                 eax, dword ptr [esp + 0xc]
            //   52                   | push                edx
            //   50                   | push                eax
            //   e8????????           |                     
            //   83c40c               | add                 esp, 0xc

        $sequence_4 = { 3b742410 7e04 89742410 8b44241c 33ff 50 897c2418 }
            // n = 7, score = 100
            //   3b742410             | cmp                 esi, dword ptr [esp + 0x10]
            //   7e04                 | jle                 6
            //   89742410             | mov                 dword ptr [esp + 0x10], esi
            //   8b44241c             | mov                 eax, dword ptr [esp + 0x1c]
            //   33ff                 | xor                 edi, edi
            //   50                   | push                eax
            //   897c2418             | mov                 dword ptr [esp + 0x18], edi

        $sequence_5 = { 89442450 894c244c e9???????? 83c8ff 8944244c 89442450 e9???????? }
            // n = 7, score = 100
            //   89442450             | mov                 dword ptr [esp + 0x50], eax
            //   894c244c             | mov                 dword ptr [esp + 0x4c], ecx
            //   e9????????           |                     
            //   83c8ff               | or                  eax, 0xffffffff
            //   8944244c             | mov                 dword ptr [esp + 0x4c], eax
            //   89442450             | mov                 dword ptr [esp + 0x50], eax
            //   e9????????           |                     

        $sequence_6 = { 896c2418 8be8 f7d5 23eb 8b5c2428 23c3 0be8 }
            // n = 7, score = 100
            //   896c2418             | mov                 dword ptr [esp + 0x18], ebp
            //   8be8                 | mov                 ebp, eax
            //   f7d5                 | not                 ebp
            //   23eb                 | and                 ebp, ebx
            //   8b5c2428             | mov                 ebx, dword ptr [esp + 0x28]
            //   23c3                 | and                 eax, ebx
            //   0be8                 | or                  ebp, eax

        $sequence_7 = { 8b842480000000 8dac28dcbc1b8f 8bc5 c1e81a c1e506 0bc5 8b6c241c }
            // n = 7, score = 100
            //   8b842480000000       | mov                 eax, dword ptr [esp + 0x80]
            //   8dac28dcbc1b8f       | lea                 ebp, dword ptr [eax + ebp - 0x70e44324]
            //   8bc5                 | mov                 eax, ebp
            //   c1e81a               | shr                 eax, 0x1a
            //   c1e506               | shl                 ebp, 6
            //   0bc5                 | or                  eax, ebp
            //   8b6c241c             | mov                 ebp, dword ptr [esp + 0x1c]

        $sequence_8 = { 89859c040000 8b442430 898598040000 c7859c04000001000000 8bb598040000 6a06 56 }
            // n = 7, score = 100
            //   89859c040000         | mov                 dword ptr [ebp + 0x49c], eax
            //   8b442430             | mov                 eax, dword ptr [esp + 0x30]
            //   898598040000         | mov                 dword ptr [ebp + 0x498], eax
            //   c7859c04000001000000     | mov    dword ptr [ebp + 0x49c], 1
            //   8bb598040000         | mov                 esi, dword ptr [ebp + 0x498]
            //   6a06                 | push                6
            //   56                   | push                esi

        $sequence_9 = { 5e 5d b852dfffff 5b 83c42c c3 837c243030 }
            // n = 7, score = 100
            //   5e                   | pop                 esi
            //   5d                   | pop                 ebp
            //   b852dfffff           | mov                 eax, 0xffffdf52
            //   5b                   | pop                 ebx
            //   83c42c               | add                 esp, 0x2c
            //   c3                   | ret                 
            //   837c243030           | cmp                 dword ptr [esp + 0x30], 0x30

    condition:
        7 of them and filesize < 1867776
}