rule win_newcore_rat_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2023-03-28"
        version = "1"
        description = "Detects win.newcore_rat."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.newcore_rat"
        malpedia_rule_date = "20230328"
        malpedia_hash = "9d2d75cef573c1c2d861f5197df8f563b05a305d"
        malpedia_version = "20230407"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 8b4204 ffd0 6852020000 8d4c2450 51 8d4c243c e8???????? }
            // n = 7, score = 100
            //   8b4204               | mov                 eax, dword ptr [edx + 4]
            //   ffd0                 | call                eax
            //   6852020000           | push                0x252
            //   8d4c2450             | lea                 ecx, [esp + 0x50]
            //   51                   | push                ecx
            //   8d4c243c             | lea                 ecx, [esp + 0x3c]
            //   e8????????           |                     

        $sequence_1 = { ffd2 8bf8 85ff 7519 894500 8b44241c 8938 }
            // n = 7, score = 100
            //   ffd2                 | call                edx
            //   8bf8                 | mov                 edi, eax
            //   85ff                 | test                edi, edi
            //   7519                 | jne                 0x1b
            //   894500               | mov                 dword ptr [ebp], eax
            //   8b44241c             | mov                 eax, dword ptr [esp + 0x1c]
            //   8938                 | mov                 dword ptr [eax], edi

        $sequence_2 = { 55 c70300002000 e8???????? 57 e8???????? }
            // n = 5, score = 100
            //   55                   | push                ebp
            //   c70300002000         | mov                 dword ptr [ebx], 0x200000
            //   e8????????           |                     
            //   57                   | push                edi
            //   e8????????           |                     

        $sequence_3 = { 7431 83f8ff 742c 8b4c2424 2944240c 03c8 }
            // n = 6, score = 100
            //   7431                 | je                  0x33
            //   83f8ff               | cmp                 eax, -1
            //   742c                 | je                  0x2e
            //   8b4c2424             | mov                 ecx, dword ptr [esp + 0x24]
            //   2944240c             | sub                 dword ptr [esp + 0xc], eax
            //   03c8                 | add                 ecx, eax

        $sequence_4 = { 33c9 68fe010000 51 8d542422 52 89442420 66894c2424 }
            // n = 7, score = 100
            //   33c9                 | xor                 ecx, ecx
            //   68fe010000           | push                0x1fe
            //   51                   | push                ecx
            //   8d542422             | lea                 edx, [esp + 0x22]
            //   52                   | push                edx
            //   89442420             | mov                 dword ptr [esp + 0x20], eax
            //   66894c2424           | mov                 word ptr [esp + 0x24], cx

        $sequence_5 = { c784249c0a000000000000 e8???????? 8d4c2414 85c0 0f84be040000 }
            // n = 5, score = 100
            //   c784249c0a000000000000     | mov    dword ptr [esp + 0xa9c], 0
            //   e8????????           |                     
            //   8d4c2414             | lea                 ecx, [esp + 0x14]
            //   85c0                 | test                eax, eax
            //   0f84be040000         | je                  0x4c4

        $sequence_6 = { 8bd8 83c408 3bde 0f8431010000 8b442474 3bc6 7625 }
            // n = 7, score = 100
            //   8bd8                 | mov                 ebx, eax
            //   83c408               | add                 esp, 8
            //   3bde                 | cmp                 ebx, esi
            //   0f8431010000         | je                  0x137
            //   8b442474             | mov                 eax, dword ptr [esp + 0x74]
            //   3bc6                 | cmp                 eax, esi
            //   7625                 | jbe                 0x27

        $sequence_7 = { eb02 0430 83e10f 88445414 8bc1 83f809 }
            // n = 6, score = 100
            //   eb02                 | jmp                 4
            //   0430                 | add                 al, 0x30
            //   83e10f               | and                 ecx, 0xf
            //   88445414             | mov                 byte ptr [esp + edx*2 + 0x14], al
            //   8bc1                 | mov                 eax, ecx
            //   83f809               | cmp                 eax, 9

        $sequence_8 = { 8d41fc 8b4c2404 2bc1 c3 55 8bec 83ec08 }
            // n = 7, score = 100
            //   8d41fc               | lea                 eax, [ecx - 4]
            //   8b4c2404             | mov                 ecx, dword ptr [esp + 4]
            //   2bc1                 | sub                 eax, ecx
            //   c3                   | ret                 
            //   55                   | push                ebp
            //   8bec                 | mov                 ebp, esp
            //   83ec08               | sub                 esp, 8

        $sequence_9 = { 50 c744243800000000 c744243c00000000 e8???????? 83c40c 8d8c2484020000 6800010000 }
            // n = 7, score = 100
            //   50                   | push                eax
            //   c744243800000000     | mov                 dword ptr [esp + 0x38], 0
            //   c744243c00000000     | mov                 dword ptr [esp + 0x3c], 0
            //   e8????????           |                     
            //   83c40c               | add                 esp, 0xc
            //   8d8c2484020000       | lea                 ecx, [esp + 0x284]
            //   6800010000           | push                0x100

    condition:
        7 of them and filesize < 581632
}