rule win_leash_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2021-06-10"
        version = "1"
        description = "Detects win.leash."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.leash"
        malpedia_rule_date = "20210604"
        malpedia_hash = "be09d5d71e77373c0f538068be31a2ad4c69cfbd"
        malpedia_version = "20210616"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 095afc 8b5c2428 41 4b 895c2428 75cc 8b5c2434 }
            // n = 7, score = 200
            //   095afc               | or                  dword ptr [edx - 4], ebx
            //   8b5c2428             | mov                 ebx, dword ptr [esp + 0x28]
            //   41                   | inc                 ecx
            //   4b                   | dec                 ebx
            //   895c2428             | mov                 dword ptr [esp + 0x28], ebx
            //   75cc                 | jne                 0xffffffce
            //   8b5c2434             | mov                 ebx, dword ptr [esp + 0x34]

        $sequence_1 = { 8d4da8 e9???????? 8d4da0 e9???????? 8d4dc8 e9???????? 8d4dc8 }
            // n = 7, score = 200
            //   8d4da8               | lea                 ecx, dword ptr [ebp - 0x58]
            //   e9????????           |                     
            //   8d4da0               | lea                 ecx, dword ptr [ebp - 0x60]
            //   e9????????           |                     
            //   8d4dc8               | lea                 ecx, dword ptr [ebp - 0x38]
            //   e9????????           |                     
            //   8d4dc8               | lea                 ecx, dword ptr [ebp - 0x38]

        $sequence_2 = { 6a03 f7f9 8d859cfcffff 50 52 e8???????? b940000000 }
            // n = 7, score = 200
            //   6a03                 | push                3
            //   f7f9                 | idiv                ecx
            //   8d859cfcffff         | lea                 eax, dword ptr [ebp - 0x364]
            //   50                   | push                eax
            //   52                   | push                edx
            //   e8????????           |                     
            //   b940000000           | mov                 ecx, 0x40

        $sequence_3 = { 83c40c 8d95e4f7ffff 8d8819100000 51 8d88190c0000 52 }
            // n = 6, score = 200
            //   83c40c               | add                 esp, 0xc
            //   8d95e4f7ffff         | lea                 edx, dword ptr [ebp - 0x81c]
            //   8d8819100000         | lea                 ecx, dword ptr [eax + 0x1019]
            //   51                   | push                ecx
            //   8d88190c0000         | lea                 ecx, dword ptr [eax + 0xc19]
            //   52                   | push                edx

        $sequence_4 = { 83c9ff 33c0 33d2 33ed 8d9c241c100000 }
            // n = 5, score = 200
            //   83c9ff               | or                  ecx, 0xffffffff
            //   33c0                 | xor                 eax, eax
            //   33d2                 | xor                 edx, edx
            //   33ed                 | xor                 ebp, ebp
            //   8d9c241c100000       | lea                 ebx, dword ptr [esp + 0x101c]

        $sequence_5 = { 3bc3 8d4dc4 0f9d45ef c645fc02 e8???????? 385def }
            // n = 6, score = 200
            //   3bc3                 | cmp                 eax, ebx
            //   8d4dc4               | lea                 ecx, dword ptr [ebp - 0x3c]
            //   0f9d45ef             | setge               byte ptr [ebp - 0x11]
            //   c645fc02             | mov                 byte ptr [ebp - 4], 2
            //   e8????????           |                     
            //   385def               | cmp                 byte ptr [ebp - 0x11], bl

        $sequence_6 = { 0f8c0bffffff 33c0 85db 89442444 0f8eb2000000 8b742420 8b4c2414 }
            // n = 7, score = 200
            //   0f8c0bffffff         | jl                  0xffffff11
            //   33c0                 | xor                 eax, eax
            //   85db                 | test                ebx, ebx
            //   89442444             | mov                 dword ptr [esp + 0x44], eax
            //   0f8eb2000000         | jle                 0xb8
            //   8b742420             | mov                 esi, dword ptr [esp + 0x20]
            //   8b4c2414             | mov                 ecx, dword ptr [esp + 0x14]

        $sequence_7 = { 83c408 33f6 85db 8be8 7e48 8b7c2444 33c9 }
            // n = 7, score = 200
            //   83c408               | add                 esp, 8
            //   33f6                 | xor                 esi, esi
            //   85db                 | test                ebx, ebx
            //   8be8                 | mov                 ebp, eax
            //   7e48                 | jle                 0x4a
            //   8b7c2444             | mov                 edi, dword ptr [esp + 0x44]
            //   33c9                 | xor                 ecx, ecx

        $sequence_8 = { f6c301 5b 7409 8d4c2404 e8???????? 8d4c2418 c7442410ffffffff }
            // n = 7, score = 200
            //   f6c301               | test                bl, 1
            //   5b                   | pop                 ebx
            //   7409                 | je                  0xb
            //   8d4c2404             | lea                 ecx, dword ptr [esp + 4]
            //   e8????????           |                     
            //   8d4c2418             | lea                 ecx, dword ptr [esp + 0x18]
            //   c7442410ffffffff     | mov                 dword ptr [esp + 0x10], 0xffffffff

        $sequence_9 = { e8???????? 3bf0 8bce 7f02 8bc8 8b15???????? 8955ec }
            // n = 7, score = 200
            //   e8????????           |                     
            //   3bf0                 | cmp                 esi, eax
            //   8bce                 | mov                 ecx, esi
            //   7f02                 | jg                  4
            //   8bc8                 | mov                 ecx, eax
            //   8b15????????         |                     
            //   8955ec               | mov                 dword ptr [ebp - 0x14], edx

    condition:
        7 of them and filesize < 761856
}