rule win_keyhole_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-09-17"
        version = "1"
        description = "Detects win.keyhole."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.keyhole"
        malpedia_rule_date = "20260916"
        malpedia_hash = "53a643781c18e08f4a50949af60172d837a0b6f6"
        malpedia_version = "20260917"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 895848 8be9 8bfb 83f908 0f8290000000 8bd6 8bf2 }
            // n = 7, score = 100
            //   895848               | mov                 dword ptr [eax + 0x48], ebx
            //   8be9                 | mov                 ebp, ecx
            //   8bfb                 | mov                 edi, ebx
            //   83f908               | cmp                 ecx, 8
            //   0f8290000000         | jb                  0x96
            //   8bd6                 | mov                 edx, esi
            //   8bf2                 | mov                 esi, edx

        $sequence_1 = { 7507 0f31 a3???????? ba???????? 6902fd430300 2bdf 43 }
            // n = 7, score = 100
            //   7507                 | jne                 9
            //   0f31                 | rdtsc               
            //   a3????????           |                     
            //   ba????????           |                     
            //   6902fd430300         | imul                eax, dword ptr [edx], 0x343fd
            //   2bdf                 | sub                 ebx, edi
            //   43                   | inc                 ebx

        $sequence_2 = { d3e0 0bd0 83fe0f 0f8254ffffff e9???????? 0fb65301 8d4e08 }
            // n = 7, score = 100
            //   d3e0                 | shl                 eax, cl
            //   0bd0                 | or                  edx, eax
            //   83fe0f               | cmp                 esi, 0xf
            //   0f8254ffffff         | jb                  0xffffff5a
            //   e9????????           |                     
            //   0fb65301             | movzx               edx, byte ptr [ebx + 1]
            //   8d4e08               | lea                 ecx, [esi + 8]

        $sequence_3 = { 68???????? e8???????? 8d442434 50 68???????? e8???????? 83c43c }
            // n = 7, score = 100
            //   68????????           |                     
            //   e8????????           |                     
            //   8d442434             | lea                 eax, [esp + 0x34]
            //   50                   | push                eax
            //   68????????           |                     
            //   e8????????           |                     
            //   83c43c               | add                 esp, 0x3c

        $sequence_4 = { 50 56 e8???????? 8d442444 c744244006000000 50 }
            // n = 6, score = 100
            //   50                   | push                eax
            //   56                   | push                esi
            //   e8????????           |                     
            //   8d442444             | lea                 eax, [esp + 0x44]
            //   c744244006000000     | mov                 dword ptr [esp + 0x40], 6
            //   50                   | push                eax

        $sequence_5 = { 8bf8 85ff 7438 8d442414 50 ff742414 8d4e07 }
            // n = 7, score = 100
            //   8bf8                 | mov                 edi, eax
            //   85ff                 | test                edi, edi
            //   7438                 | je                  0x3a
            //   8d442414             | lea                 eax, [esp + 0x14]
            //   50                   | push                eax
            //   ff742414             | push                dword ptr [esp + 0x14]
            //   8d4e07               | lea                 ecx, [esi + 7]

        $sequence_6 = { ffb42480000000 8d442420 50 8d442444 50 ff15???????? 83c414 }
            // n = 7, score = 100
            //   ffb42480000000       | push                dword ptr [esp + 0x80]
            //   8d442420             | lea                 eax, [esp + 0x20]
            //   50                   | push                eax
            //   8d442444             | lea                 eax, [esp + 0x44]
            //   50                   | push                eax
            //   ff15????????         |                     
            //   83c414               | add                 esp, 0x14

        $sequence_7 = { 8b542414 88642413 84e4 7420 025c2413 8ac2 2a442424 }
            // n = 7, score = 100
            //   8b542414             | mov                 edx, dword ptr [esp + 0x14]
            //   88642413             | mov                 byte ptr [esp + 0x13], ah
            //   84e4                 | test                ah, ah
            //   7420                 | je                  0x22
            //   025c2413             | add                 bl, byte ptr [esp + 0x13]
            //   8ac2                 | mov                 al, dl
            //   2a442424             | sub                 al, byte ptr [esp + 0x24]

        $sequence_8 = { 03f9 03c8 0fb64607 83c608 03f9 03c8 03f9 }
            // n = 7, score = 100
            //   03f9                 | add                 edi, ecx
            //   03c8                 | add                 ecx, eax
            //   0fb64607             | movzx               eax, byte ptr [esi + 7]
            //   83c608               | add                 esi, 8
            //   03f9                 | add                 edi, ecx
            //   03c8                 | add                 ecx, eax
            //   03f9                 | add                 edi, ecx

        $sequence_9 = { 57 ffd6 a3???????? 85c0 0f849d000000 8d44240c 50 }
            // n = 7, score = 100
            //   57                   | push                edi
            //   ffd6                 | call                esi
            //   a3????????           |                     
            //   85c0                 | test                eax, eax
            //   0f849d000000         | je                  0xa3
            //   8d44240c             | lea                 eax, [esp + 0xc]
            //   50                   | push                eax

    condition:
        7 of them and filesize < 303104
}