rule win_buzus_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2022-05-16"
        version = "1"
        description = "Detects win.buzus."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.buzus"
        malpedia_rule_date = "20220513"
        malpedia_hash = "7f4b2229e6ae614d86d74917f6d5b41890e62a26"
        malpedia_version = "20220516"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { ff15???????? 8b4510 895df8 8945f4 8d45f4 50 8d85e0feffff }
            // n = 7, score = 100
            //   ff15????????         |                     
            //   8b4510               | mov                 eax, dword ptr [ebp + 0x10]
            //   895df8               | mov                 dword ptr [ebp - 8], ebx
            //   8945f4               | mov                 dword ptr [ebp - 0xc], eax
            //   8d45f4               | lea                 eax, [ebp - 0xc]
            //   50                   | push                eax
            //   8d85e0feffff         | lea                 eax, [ebp - 0x120]

        $sequence_1 = { bf???????? 0f95c2 8955c8 33d2 395e10 50 }
            // n = 6, score = 100
            //   bf????????           |                     
            //   0f95c2               | setne               dl
            //   8955c8               | mov                 dword ptr [ebp - 0x38], edx
            //   33d2                 | xor                 edx, edx
            //   395e10               | cmp                 dword ptr [esi + 0x10], ebx
            //   50                   | push                eax

        $sequence_2 = { 50 ff15???????? 83c40c 8d85d8fbffff 50 ff15???????? 85c0 }
            // n = 7, score = 100
            //   50                   | push                eax
            //   ff15????????         |                     
            //   83c40c               | add                 esp, 0xc
            //   8d85d8fbffff         | lea                 eax, [ebp - 0x428]
            //   50                   | push                eax
            //   ff15????????         |                     
            //   85c0                 | test                eax, eax

        $sequence_3 = { 837db401 0f94c0 50 6a01 e8???????? 68???????? ff7508 }
            // n = 7, score = 100
            //   837db401             | cmp                 dword ptr [ebp - 0x4c], 1
            //   0f94c0               | sete                al
            //   50                   | push                eax
            //   6a01                 | push                1
            //   e8????????           |                     
            //   68????????           |                     
            //   ff7508               | push                dword ptr [ebp + 8]

        $sequence_4 = { c7852cfeffff98d04000 c78530feffff8cd04000 c78534feffff80d04000 c78538feffff74d04000 c7853cfeffff68d04000 c78540feffff5cd04000 c78544feffff54d04000 }
            // n = 7, score = 100
            //   c7852cfeffff98d04000     | mov    dword ptr [ebp - 0x1d4], 0x40d098
            //   c78530feffff8cd04000     | mov    dword ptr [ebp - 0x1d0], 0x40d08c
            //   c78534feffff80d04000     | mov    dword ptr [ebp - 0x1cc], 0x40d080
            //   c78538feffff74d04000     | mov    dword ptr [ebp - 0x1c8], 0x40d074
            //   c7853cfeffff68d04000     | mov    dword ptr [ebp - 0x1c4], 0x40d068
            //   c78540feffff5cd04000     | mov    dword ptr [ebp - 0x1c0], 0x40d05c
            //   c78544feffff54d04000     | mov    dword ptr [ebp - 0x1bc], 0x40d054

        $sequence_5 = { ffd6 8945fc 8b45f0 3bc7 7502 ffd6 c1e008 }
            // n = 7, score = 100
            //   ffd6                 | call                esi
            //   8945fc               | mov                 dword ptr [ebp - 4], eax
            //   8b45f0               | mov                 eax, dword ptr [ebp - 0x10]
            //   3bc7                 | cmp                 eax, edi
            //   7502                 | jne                 4
            //   ffd6                 | call                esi
            //   c1e008               | shl                 eax, 8

        $sequence_6 = { 83fa7f 7505 ffd6 99 ebef }
            // n = 5, score = 100
            //   83fa7f               | cmp                 edx, 0x7f
            //   7505                 | jne                 7
            //   ffd6                 | call                esi
            //   99                   | cdq                 
            //   ebef                 | jmp                 0xfffffff1

        $sequence_7 = { 57 6a02 897dfc ff15???????? 8bf0 83feff 7471 }
            // n = 7, score = 100
            //   57                   | push                edi
            //   6a02                 | push                2
            //   897dfc               | mov                 dword ptr [ebp - 4], edi
            //   ff15????????         |                     
            //   8bf0                 | mov                 esi, eax
            //   83feff               | cmp                 esi, -1
            //   7471                 | je                  0x73

        $sequence_8 = { 56 e8???????? 83c428 395d1c 0f85b2030000 395d24 0f84a9030000 }
            // n = 7, score = 100
            //   56                   | push                esi
            //   e8????????           |                     
            //   83c428               | add                 esp, 0x28
            //   395d1c               | cmp                 dword ptr [ebp + 0x1c], ebx
            //   0f85b2030000         | jne                 0x3b8
            //   395d24               | cmp                 dword ptr [ebp + 0x24], ebx
            //   0f84a9030000         | je                  0x3af

        $sequence_9 = { 8d8534ffffff 50 e8???????? 8b4e08 8b4604 33d2 395e0c }
            // n = 7, score = 100
            //   8d8534ffffff         | lea                 eax, [ebp - 0xcc]
            //   50                   | push                eax
            //   e8????????           |                     
            //   8b4e08               | mov                 ecx, dword ptr [esi + 8]
            //   8b4604               | mov                 eax, dword ptr [esi + 4]
            //   33d2                 | xor                 edx, edx
            //   395e0c               | cmp                 dword ptr [esi + 0xc], ebx

    condition:
        7 of them and filesize < 679936
}