rule win_murofet_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-05-04"
        version = "1"
        description = "Detects win.murofet."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.murofet"
        malpedia_rule_date = "20260422"
        malpedia_hash = "a182e35da64e6d71cb55f125c4d4225196523f14"
        malpedia_version = "20260504"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { e8???????? 3c02 72e5 e8???????? a2???????? 84c0 7510 }
            // n = 7, score = 400
            //   e8????????           |                     
            //   3c02                 | cmp                 al, 2
            //   72e5                 | jb                  0xffffffe7
            //   e8????????           |                     
            //   a2????????           |                     
            //   84c0                 | test                al, al
            //   7510                 | jne                 0x12

        $sequence_1 = { e8???????? a2???????? 84c0 7510 e8???????? 3c04 73ce }
            // n = 7, score = 400
            //   e8????????           |                     
            //   a2????????           |                     
            //   84c0                 | test                al, al
            //   7510                 | jne                 0x12
            //   e8????????           |                     
            //   3c04                 | cmp                 al, 4
            //   73ce                 | jae                 0xffffffd0

        $sequence_2 = { e8???????? 32c0 eb43 be30750000 56 }
            // n = 5, score = 400
            //   e8????????           |                     
            //   32c0                 | xor                 al, al
            //   eb43                 | jmp                 0x45
            //   be30750000           | mov                 esi, 0x7530
            //   56                   | push                esi

        $sequence_3 = { 8816 e8???????? 0fb6c0 99 f7ff }
            // n = 5, score = 400
            //   8816                 | mov                 byte ptr [esi], dl
            //   e8????????           |                     
            //   0fb6c0               | movzx               eax, al
            //   99                   | cdq                 
            //   f7ff                 | idiv                edi

        $sequence_4 = { e8???????? 0fb6c0 99 bfff000000 }
            // n = 4, score = 400
            //   e8????????           |                     
            //   0fb6c0               | movzx               eax, al
            //   99                   | cdq                 
            //   bfff000000           | mov                 edi, 0xff

        $sequence_5 = { 53 57 56 ff15???????? c6443eff00 83f8ff }
            // n = 6, score = 400
            //   53                   | push                ebx
            //   57                   | push                edi
            //   56                   | push                esi
            //   ff15????????         |                     
            //   c6443eff00           | mov                 byte ptr [esi + edi - 1], 0
            //   83f8ff               | cmp                 eax, -1

        $sequence_6 = { 7504 3c02 72bf b001 }
            // n = 4, score = 400
            //   7504                 | jne                 6
            //   3c02                 | cmp                 al, 2
            //   72bf                 | jb                  0xffffffc1
            //   b001                 | mov                 al, 1

        $sequence_7 = { e8???????? 32c0 eb43 be30750000 56 6a04 }
            // n = 6, score = 400
            //   e8????????           |                     
            //   32c0                 | xor                 al, al
            //   eb43                 | jmp                 0x45
            //   be30750000           | mov                 esi, 0x7530
            //   56                   | push                esi
            //   6a04                 | push                4

        $sequence_8 = { 50 53 57 56 ff15???????? c6443eff00 83f8ff }
            // n = 7, score = 400
            //   50                   | push                eax
            //   53                   | push                ebx
            //   57                   | push                edi
            //   56                   | push                esi
            //   ff15????????         |                     
            //   c6443eff00           | mov                 byte ptr [esi + edi - 1], 0
            //   83f8ff               | cmp                 eax, -1

        $sequence_9 = { fec2 8816 e8???????? 0fb6c0 99 f7ff }
            // n = 6, score = 400
            //   fec2                 | inc                 dl
            //   8816                 | mov                 byte ptr [esi], dl
            //   e8????????           |                     
            //   0fb6c0               | movzx               eax, al
            //   99                   | cdq                 
            //   f7ff                 | idiv                edi

    condition:
        7 of them and filesize < 622592
}