rule win_zeus_openssl_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2022-11-21"
        version = "1"
        description = "Detects win.zeus_openssl."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.zeus_openssl"
        malpedia_rule_date = "20221118"
        malpedia_hash = "e0702e2e6d1d00da65c8a29a4ebacd0a4c59e1af"
        malpedia_version = "20221125"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { ba10000000 83fb0a 0f8fed000000 0fb7b0c20a0000 2bd6 8975e4 3bca }
            // n = 7, score = 1300
            //   ba10000000           | mov                 edx, 0x10
            //   83fb0a               | cmp                 ebx, 0xa
            //   0f8fed000000         | jg                  0xf3
            //   0fb7b0c20a0000       | movzx               esi, word ptr [eax + 0xac2]
            //   2bd6                 | sub                 edx, esi
            //   8975e4               | mov                 dword ptr [ebp - 0x1c], esi
            //   3bca                 | cmp                 ecx, edx

        $sequence_1 = { 89426c 894250 89424c c70200000000 }
            // n = 4, score = 1300
            //   89426c               | mov                 dword ptr [edx + 0x6c], eax
            //   894250               | mov                 dword ptr [edx + 0x50], eax
            //   89424c               | mov                 dword ptr [edx + 0x4c], eax
            //   c70200000000         | mov                 dword ptr [edx], 0

        $sequence_2 = { 8bf1 8b7e74 81ff02010000 7722 8bce }
            // n = 5, score = 1300
            //   8bf1                 | mov                 esi, ecx
            //   8b7e74               | mov                 edi, dword ptr [esi + 0x74]
            //   81ff02010000         | cmp                 edi, 0x102
            //   7722                 | ja                  0x24
            //   8bce                 | mov                 ecx, esi

        $sequence_3 = { 8b5dfc 83e00f 894148 c70117000000 }
            // n = 4, score = 1300
            //   8b5dfc               | mov                 ebx, dword ptr [ebp - 4]
            //   83e00f               | and                 eax, 0xf
            //   894148               | mov                 dword ptr [ecx + 0x48], eax
            //   c70117000000         | mov                 dword ptr [ecx], 0x17

        $sequence_4 = { 8bce c7460471000000 e8???????? 837e6c00 7416 0fb75732 8bce }
            // n = 7, score = 1300
            //   8bce                 | mov                 ecx, esi
            //   c7460471000000       | mov                 dword ptr [esi + 4], 0x71
            //   e8????????           |                     
            //   837e6c00             | cmp                 dword ptr [esi + 0x6c], 0
            //   7416                 | je                  0x18
            //   0fb75732             | movzx               edx, word ptr [edi + 0x32]
            //   8bce                 | mov                 ecx, esi

        $sequence_5 = { 8b55ec 8945e4 8b45ec 0fb60406 0345e4 }
            // n = 5, score = 1300
            //   8b55ec               | mov                 edx, dword ptr [ebp - 0x14]
            //   8945e4               | mov                 dword ptr [ebp - 0x1c], eax
            //   8b45ec               | mov                 eax, dword ptr [ebp - 0x14]
            //   0fb60406             | movzx               eax, byte ptr [esi + eax]
            //   0345e4               | add                 eax, dword ptr [ebp - 0x1c]

        $sequence_6 = { 84c0 7907 814a1800300000 8a6207 84e4 7543 }
            // n = 6, score = 1300
            //   84c0                 | test                al, al
            //   7907                 | jns                 9
            //   814a1800300000       | or                  dword ptr [edx + 0x18], 0x3000
            //   8a6207               | mov                 ah, byte ptr [edx + 7]
            //   84e4                 | test                ah, ah
            //   7543                 | jne                 0x45

        $sequence_7 = { 668944bb02 8996600b0000 42 8955f8 6a01 }
            // n = 5, score = 1300
            //   668944bb02           | mov                 word ptr [ebx + edi*4 + 2], ax
            //   8996600b0000         | mov                 dword ptr [esi + 0xb60], edx
            //   42                   | inc                 edx
            //   8955f8               | mov                 dword ptr [ebp - 8], edx
            //   6a01                 | push                1

        $sequence_8 = { 83c608 03d0 895dfc 8955f8 897df0 3b75cc 72dc }
            // n = 7, score = 1300
            //   83c608               | add                 esi, 8
            //   03d0                 | add                 edx, eax
            //   895dfc               | mov                 dword ptr [ebp - 4], ebx
            //   8955f8               | mov                 dword ptr [ebp - 8], edx
            //   897df0               | mov                 dword ptr [ebp - 0x10], edi
            //   3b75cc               | cmp                 esi, dword ptr [ebp - 0x34]
            //   72dc                 | jb                  0xffffffde

        $sequence_9 = { 740d 8b4204 5e 8b08 ff4208 894a04 c3 }
            // n = 7, score = 1300
            //   740d                 | je                  0xf
            //   8b4204               | mov                 eax, dword ptr [edx + 4]
            //   5e                   | pop                 esi
            //   8b08                 | mov                 ecx, dword ptr [eax]
            //   ff4208               | inc                 dword ptr [edx + 8]
            //   894a04               | mov                 dword ptr [edx + 4], ecx
            //   c3                   | ret                 

    condition:
        7 of them and filesize < 4546560
}