rule win_avzhan_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2022-08-05"
        version = "1"
        description = "Detects win.avzhan."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.avzhan"
        malpedia_rule_date = "20220805"
        malpedia_hash = "6ec06c64bcfdbeda64eff021c766b4ce34542b71"
        malpedia_version = "20220808"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { e8???????? 8d8c24e8000000 8d542468 51 8d842484010000 }
            // n = 5, score = 200
            //   e8????????           |                     
            //   8d8c24e8000000       | lea                 ecx, [esp + 0xe8]
            //   8d542468             | lea                 edx, [esp + 0x68]
            //   51                   | push                ecx
            //   8d842484010000       | lea                 eax, [esp + 0x184]

        $sequence_1 = { 3935???????? 7450 8b942464010000 8d442464 52 50 }
            // n = 6, score = 200
            //   3935????????         |                     
            //   7450                 | je                  0x52
            //   8b942464010000       | mov                 edx, dword ptr [esp + 0x164]
            //   8d442464             | lea                 eax, [esp + 0x64]
            //   52                   | push                edx
            //   50                   | push                eax

        $sequence_2 = { 3935???????? 7450 8b942464010000 8d442464 52 50 e8???????? }
            // n = 7, score = 200
            //   3935????????         |                     
            //   7450                 | je                  0x52
            //   8b942464010000       | mov                 edx, dword ptr [esp + 0x164]
            //   8d442464             | lea                 eax, [esp + 0x64]
            //   52                   | push                edx
            //   50                   | push                eax
            //   e8????????           |                     

        $sequence_3 = { 8af2 83c408 8bc2 c1e010 668bc2 }
            // n = 5, score = 200
            //   8af2                 | mov                 dh, dl
            //   83c408               | add                 esp, 8
            //   8bc2                 | mov                 eax, edx
            //   c1e010               | shl                 eax, 0x10
            //   668bc2               | mov                 ax, dx

        $sequence_4 = { f3ab 8b442464 8b3d???????? 83c418 }
            // n = 4, score = 200
            //   f3ab                 | rep stosd           dword ptr es:[edi], eax
            //   8b442464             | mov                 eax, dword ptr [esp + 0x64]
            //   8b3d????????         |                     
            //   83c418               | add                 esp, 0x18

        $sequence_5 = { 51 8d8424ec000000 52 50 68???????? eb1d 6a02 }
            // n = 7, score = 200
            //   51                   | push                ecx
            //   8d8424ec000000       | lea                 eax, [esp + 0xec]
            //   52                   | push                edx
            //   50                   | push                eax
            //   68????????           |                     
            //   eb1d                 | jmp                 0x1f
            //   6a02                 | push                2

        $sequence_6 = { 8af2 83c408 8bc2 c1e010 }
            // n = 4, score = 200
            //   8af2                 | mov                 dh, dl
            //   83c408               | add                 esp, 8
            //   8bc2                 | mov                 eax, edx
            //   c1e010               | shl                 eax, 0x10

        $sequence_7 = { 6a00 8b542414 52 ffd3 6a0a ffd7 ebbc }
            // n = 7, score = 200
            //   6a00                 | push                0
            //   8b542414             | mov                 edx, dword ptr [esp + 0x14]
            //   52                   | push                edx
            //   ffd3                 | call                ebx
            //   6a0a                 | push                0xa
            //   ffd7                 | call                edi
            //   ebbc                 | jmp                 0xffffffbe

        $sequence_8 = { c1e010 668bc3 8b1d???????? c1e902 f3ab 8bca 83e103 }
            // n = 7, score = 200
            //   c1e010               | shl                 eax, 0x10
            //   668bc3               | mov                 ax, bx
            //   8b1d????????         |                     
            //   c1e902               | shr                 ecx, 2
            //   f3ab                 | rep stosd           dword ptr es:[edi], eax
            //   8bca                 | mov                 ecx, edx
            //   83e103               | and                 ecx, 3

        $sequence_9 = { 8d842484010000 52 50 8d8c240c020000 68???????? 51 }
            // n = 6, score = 200
            //   8d842484010000       | lea                 eax, [esp + 0x184]
            //   52                   | push                edx
            //   50                   | push                eax
            //   8d8c240c020000       | lea                 ecx, [esp + 0x20c]
            //   68????????           |                     
            //   51                   | push                ecx

    condition:
        7 of them and filesize < 122880
}