rule win_unidentified_068_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-05-04"
        version = "1"
        description = "Detects win.unidentified_068."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_068"
        malpedia_rule_date = "20260422"
        malpedia_hash = "a182e35da64e6d71cb55f125c4d4225196523f14"
        malpedia_version = "20260504"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 8b5dd0 03c8 d1e9 3b14cb 7511 8bf3 8b5cce04 }
            // n = 7, score = 100
            //   8b5dd0               | mov                 ebx, dword ptr [ebp - 0x30]
            //   03c8                 | add                 ecx, eax
            //   d1e9                 | shr                 ecx, 1
            //   3b14cb               | cmp                 edx, dword ptr [ebx + ecx*8]
            //   7511                 | jne                 0x13
            //   8bf3                 | mov                 esi, ebx
            //   8b5cce04             | mov                 ebx, dword ptr [esi + ecx*8 + 4]

        $sequence_1 = { 663bf8 7512 8a4603 eb46 8bf2 85c0 75d8 }
            // n = 7, score = 100
            //   663bf8               | cmp                 di, ax
            //   7512                 | jne                 0x14
            //   8a4603               | mov                 al, byte ptr [esi + 3]
            //   eb46                 | jmp                 0x48
            //   8bf2                 | mov                 esi, edx
            //   85c0                 | test                eax, eax
            //   75d8                 | jne                 0xffffffda

        $sequence_2 = { 5e 8d4802 f7d8 1bc0 23c1 c3 33c0 }
            // n = 7, score = 100
            //   5e                   | pop                 esi
            //   8d4802               | lea                 ecx, [eax + 2]
            //   f7d8                 | neg                 eax
            //   1bc0                 | sbb                 eax, eax
            //   23c1                 | and                 eax, ecx
            //   c3                   | ret                 
            //   33c0                 | xor                 eax, eax

        $sequence_3 = { c746040a000000 8b7604 57 ff15???????? 5f 8bc6 5e }
            // n = 7, score = 100
            //   c746040a000000       | mov                 dword ptr [esi + 4], 0xa
            //   8b7604               | mov                 esi, dword ptr [esi + 4]
            //   57                   | push                edi
            //   ff15????????         |                     
            //   5f                   | pop                 edi
            //   8bc6                 | mov                 eax, esi
            //   5e                   | pop                 esi

        $sequence_4 = { 7410 8b4dec 33c0 0345f0 8902 83d100 894a04 }
            // n = 7, score = 100
            //   7410                 | je                  0x12
            //   8b4dec               | mov                 ecx, dword ptr [ebp - 0x14]
            //   33c0                 | xor                 eax, eax
            //   0345f0               | add                 eax, dword ptr [ebp - 0x10]
            //   8902                 | mov                 dword ptr [edx], eax
            //   83d100               | adc                 ecx, 0
            //   894a04               | mov                 dword ptr [edx + 4], ecx

        $sequence_5 = { c74114f80c4500 894120 894124 894134 894140 894148 894158 }
            // n = 7, score = 100
            //   c74114f80c4500       | mov                 dword ptr [ecx + 0x14], 0x450cf8
            //   894120               | mov                 dword ptr [ecx + 0x20], eax
            //   894124               | mov                 dword ptr [ecx + 0x24], eax
            //   894134               | mov                 dword ptr [ecx + 0x34], eax
            //   894140               | mov                 dword ptr [ecx + 0x40], eax
            //   894148               | mov                 dword ptr [ecx + 0x48], eax
            //   894158               | mov                 dword ptr [ecx + 0x58], eax

        $sequence_6 = { 2bc8 8b45f4 66890c58 0bd3 83faff 0f8425010000 8b4dc8 }
            // n = 7, score = 100
            //   2bc8                 | sub                 ecx, eax
            //   8b45f4               | mov                 eax, dword ptr [ebp - 0xc]
            //   66890c58             | mov                 word ptr [eax + ebx*2], cx
            //   0bd3                 | or                  edx, ebx
            //   83faff               | cmp                 edx, -1
            //   0f8425010000         | je                  0x12b
            //   8b4dc8               | mov                 ecx, dword ptr [ebp - 0x38]

        $sequence_7 = { 014d0c 294dfc 8945ec 8b4510 0108 8b4728 8b4f20 }
            // n = 7, score = 100
            //   014d0c               | add                 dword ptr [ebp + 0xc], ecx
            //   294dfc               | sub                 dword ptr [ebp - 4], ecx
            //   8945ec               | mov                 dword ptr [ebp - 0x14], eax
            //   8b4510               | mov                 eax, dword ptr [ebp + 0x10]
            //   0108                 | add                 dword ptr [eax], ecx
            //   8b4728               | mov                 eax, dword ptr [edi + 0x28]
            //   8b4f20               | mov                 ecx, dword ptr [edi + 0x20]

        $sequence_8 = { 8bbd70ffffff 8b4584 2bc7 897de8 8945d8 8b458c }
            // n = 6, score = 100
            //   8bbd70ffffff         | mov                 edi, dword ptr [ebp - 0x90]
            //   8b4584               | mov                 eax, dword ptr [ebp - 0x7c]
            //   2bc7                 | sub                 eax, edi
            //   897de8               | mov                 dword ptr [ebp - 0x18], edi
            //   8945d8               | mov                 dword ptr [ebp - 0x28], eax
            //   8b458c               | mov                 eax, dword ptr [ebp - 0x74]

        $sequence_9 = { 740e 8a8277fb4400 8a8a97fb4400 eb0c 8a8257fb4400 8a8ab7fb4400 }
            // n = 6, score = 100
            //   740e                 | je                  0x10
            //   8a8277fb4400         | mov                 al, byte ptr [edx + 0x44fb77]
            //   8a8a97fb4400         | mov                 cl, byte ptr [edx + 0x44fb97]
            //   eb0c                 | jmp                 0xe
            //   8a8257fb4400         | mov                 al, byte ptr [edx + 0x44fb57]
            //   8a8ab7fb4400         | mov                 cl, byte ptr [edx + 0x44fbb7]

    condition:
        7 of them and filesize < 862208
}