rule win_grayrabbit_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-09-17"
        version = "1"
        description = "Detects win.grayrabbit."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.grayrabbit"
        malpedia_rule_date = "20260916"
        malpedia_hash = "53a643781c18e08f4a50949af60172d837a0b6f6"
        malpedia_version = "20260917"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 8b3403 85f6 7464 8b7df0 8d4de0 c645fc01 }
            // n = 6, score = 100
            //   8b3403               | mov                 esi, dword ptr [ebx + eax]
            //   85f6                 | test                esi, esi
            //   7464                 | je                  0x66
            //   8b7df0               | mov                 edi, dword ptr [ebp - 0x10]
            //   8d4de0               | lea                 ecx, [ebp - 0x20]
            //   c645fc01             | mov                 byte ptr [ebp - 4], 1

        $sequence_1 = { eb3a 81fb00100000 7227 8d4323 3bc3 0f86cd000000 50 }
            // n = 7, score = 100
            //   eb3a                 | jmp                 0x3c
            //   81fb00100000         | cmp                 ebx, 0x1000
            //   7227                 | jb                  0x29
            //   8d4323               | lea                 eax, [ebx + 0x23]
            //   3bc3                 | cmp                 eax, ebx
            //   0f86cd000000         | jbe                 0xd3
            //   50                   | push                eax

        $sequence_2 = { 8b7810 8bc6 2bc2 57 51 3bf8 7722 }
            // n = 7, score = 100
            //   8b7810               | mov                 edi, dword ptr [eax + 0x10]
            //   8bc6                 | mov                 eax, esi
            //   2bc2                 | sub                 eax, edx
            //   57                   | push                edi
            //   51                   | push                ecx
            //   3bf8                 | cmp                 edi, eax
            //   7722                 | ja                  0x24

        $sequence_3 = { 51 83c108 e8???????? 8b4604 5e 85c0 740b }
            // n = 7, score = 100
            //   51                   | push                ecx
            //   83c108               | add                 ecx, 8
            //   e8????????           |                     
            //   8b4604               | mov                 eax, dword ptr [esi + 4]
            //   5e                   | pop                 esi
            //   85c0                 | test                eax, eax
            //   740b                 | je                  0xd

        $sequence_4 = { 0f84e8000000 8b04951c550410 898588f8ffff 85c0 0f84ad000000 3bc3 0f84cb000000 }
            // n = 7, score = 100
            //   0f84e8000000         | je                  0xee
            //   8b04951c550410       | mov                 eax, dword ptr [edx*4 + 0x1004551c]
            //   898588f8ffff         | mov                 dword ptr [ebp - 0x778], eax
            //   85c0                 | test                eax, eax
            //   0f84ad000000         | je                  0xb3
            //   3bc3                 | cmp                 eax, ebx
            //   0f84cb000000         | je                  0xd1

        $sequence_5 = { 8bc8 e8???????? 8b45d4 894610 8d45d8 50 8d4e14 }
            // n = 7, score = 100
            //   8bc8                 | mov                 ecx, eax
            //   e8????????           |                     
            //   8b45d4               | mov                 eax, dword ptr [ebp - 0x2c]
            //   894610               | mov                 dword ptr [esi + 0x10], eax
            //   8d45d8               | lea                 eax, [ebp - 0x28]
            //   50                   | push                eax
            //   8d4e14               | lea                 ecx, [esi + 0x14]

        $sequence_6 = { 3b4f14 7d1b 84c0 0f84cf000000 8d4101 8903 8d45ec }
            // n = 7, score = 100
            //   3b4f14               | cmp                 ecx, dword ptr [edi + 0x14]
            //   7d1b                 | jge                 0x1d
            //   84c0                 | test                al, al
            //   0f84cf000000         | je                  0xd5
            //   8d4101               | lea                 eax, [ecx + 1]
            //   8903                 | mov                 dword ptr [ebx], eax
            //   8d45ec               | lea                 eax, [ebp - 0x14]

        $sequence_7 = { 8bc8 83e03f c1f906 6bd038 8b0c8df8630510 804c112802 5b }
            // n = 7, score = 100
            //   8bc8                 | mov                 ecx, eax
            //   83e03f               | and                 eax, 0x3f
            //   c1f906               | sar                 ecx, 6
            //   6bd038               | imul                edx, eax, 0x38
            //   8b0c8df8630510       | mov                 ecx, dword ptr [ecx*4 + 0x100563f8]
            //   804c112802           | or                  byte ptr [ecx + edx + 0x28], 2
            //   5b                   | pop                 ebx

        $sequence_8 = { 8a12 56 8d42df 3c5d 7605 80fa80 7253 }
            // n = 7, score = 100
            //   8a12                 | mov                 dl, byte ptr [edx]
            //   56                   | push                esi
            //   8d42df               | lea                 eax, [edx - 0x21]
            //   3c5d                 | cmp                 al, 0x5d
            //   7605                 | jbe                 7
            //   80fa80               | cmp                 dl, 0x80
            //   7253                 | jb                  0x55

        $sequence_9 = { e8???????? 895df0 8b4d08 8b4918 8bd9 894d08 85c9 }
            // n = 7, score = 100
            //   e8????????           |                     
            //   895df0               | mov                 dword ptr [ebp - 0x10], ebx
            //   8b4d08               | mov                 ecx, dword ptr [ebp + 8]
            //   8b4918               | mov                 ecx, dword ptr [ecx + 0x18]
            //   8bd9                 | mov                 ebx, ecx
            //   894d08               | mov                 dword ptr [ebp + 8], ecx
            //   85c9                 | test                ecx, ecx

    condition:
        7 of them and filesize < 744448
}